# Generated by Django 5.1.4 on 2026-07-18 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CritereQualite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referentiel",
                    models.CharField(
                        choices=[("cames", "CAMES"), ("anaq_sup", "ANAQ-Sup")],
                        max_length=20,
                        verbose_name="Référentiel",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "categorie",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Catégorie"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "ponderation",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Pondération"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Critère qualité",
                "verbose_name_plural": "Critères qualité",
                "db_table": "quality_criteres",
                "ordering": ["referentiel", "code"],
                "unique_together": {("referentiel", "code")},
            },
        ),
        migrations.CreateModel(
            name="PlanAmelioration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Action")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("realisee", "Réalisée"),
                            ("retardee", "Retardée"),
                        ],
                        default="planifiee",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "taux_avancement",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Taux d'avancement (%)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "critere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans_amelioration",
                        to="quality.criterequalite",
                        verbose_name="Critère",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans_amelioration_qualite",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan d'amélioration",
                "verbose_name_plural": "Plans d'amélioration",
                "db_table": "quality_plans_amelioration",
                "ordering": ["date_echeance"],
            },
        ),
        migrations.CreateModel(
            name="AutoEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campagne",
                    models.CharField(
                        help_text="Ex : 2025-2026",
                        max_length=50,
                        verbose_name="Campagne",
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Note"
                    ),
                ),
                (
                    "note_max",
                    models.DecimalField(
                        decimal_places=2,
                        default=4,
                        max_digits=4,
                        verbose_name="Note maximale",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evalue_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_evaluations_qualite",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Évalué par",
                    ),
                ),
                (
                    "critere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_evaluations",
                        to="quality.criterequalite",
                        verbose_name="Critère",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto-évaluation",
                "verbose_name_plural": "Auto-évaluations",
                "db_table": "quality_auto_evaluations",
                "ordering": ["-campagne", "critere__code"],
                "unique_together": {("critere", "campagne")},
            },
        ),
    ]
