# Generated by Django 5.1.4 on 2026-07-18 21:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Indicateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Code")),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "formule",
                    models.TextField(blank=True, verbose_name="Formule de calcul"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Source de la donnée"
                    ),
                ),
                (
                    "periodicite",
                    models.CharField(
                        choices=[
                            ("mensuelle", "Mensuelle"),
                            ("trimestrielle", "Trimestrielle"),
                            ("semestrielle", "Semestrielle"),
                            ("annuelle", "Annuelle"),
                        ],
                        default="trimestrielle",
                        max_length=20,
                        verbose_name="Périodicité",
                    ),
                ),
                (
                    "unite",
                    models.CharField(
                        blank=True,
                        help_text="Ex : %, FCFA, nombre.",
                        max_length=30,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "sens_amelioration",
                    models.CharField(
                        choices=[
                            ("hausse_souhaitee", "Hausse souhaitée"),
                            ("baisse_souhaitee", "Baisse souhaitée"),
                        ],
                        default="hausse_souhaitee",
                        max_length=20,
                        verbose_name="Sens d'amélioration",
                    ),
                ),
                (
                    "valeur_cible",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Valeur cible"
                    ),
                ),
                (
                    "valeur_actuelle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Recalculée automatiquement depuis la dernière mesure.",
                        max_digits=16,
                        verbose_name="Valeur actuelle",
                    ),
                ),
                (
                    "seuil_orange",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.80"),
                        max_digits=4,
                        verbose_name="Seuil orange (taux de réalisation)",
                    ),
                ),
                (
                    "seuil_rouge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.60"),
                        max_digits=4,
                        verbose_name="Seuil rouge (taux de réalisation)",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicateurs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicateur",
                "verbose_name_plural": "Indicateurs",
                "db_table": "kpi_indicateurs",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ValeurIndicateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mesure", models.DateField(verbose_name="Date de mesure")),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="Valeur mesurée"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="indicators.indicateur",
                        verbose_name="Indicateur",
                    ),
                ),
                (
                    "saisi_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mesures_indicateurs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Saisi par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valeur mesurée",
                "verbose_name_plural": "Valeurs mesurées",
                "db_table": "kpi_valeurs",
                "ordering": ["-date_mesure"],
            },
        ),
        migrations.AddIndex(
            model_name="indicateur",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="kpi_indicat_content_e9814e_idx",
            ),
        ),
    ]
