from django.urls import path
from . import views
from . import budget_views

app_name = 'accounting'

urlpatterns = [
    path('',                         views.accounting_dashboard,  name='dashboard'),
    path('taux/',                    views.hourly_rate_list,      name='rate_list'),
    path('taux/creer/',              views.hourly_rate_create,    name='rate_create'),
    path('taux/<int:pk>/modifier/',  views.hourly_rate_edit,      name='rate_edit'),
    path('taux/<int:pk>/supprimer/', views.hourly_rate_delete,    name='rate_delete'),
    path('budget-honoraires/',       views.budget_honoraires_view, name='budget_honoraires'),
    path('budget-honoraires/export/excel/', views.budget_honoraires_export_excel, name='budget_honoraires_export_excel'),
    path('budget-honoraires/export/pdf/',   views.budget_honoraires_export_pdf,   name='budget_honoraires_export_pdf'),
    path('budget-honoraires/export/word/',  views.budget_honoraires_export_word,  name='budget_honoraires_export_word'),
    path('partenaires-bourse/',                        views.partenaire_bourse_list,   name='partenaire_bourse_list'),
    path('partenaires-bourse/creer/',                  views.partenaire_bourse_create, name='partenaire_bourse_create'),
    path('partenaires-bourse/<int:pk>/modifier/',      views.partenaire_bourse_edit,   name='partenaire_bourse_edit'),
    path('partenaires-bourse/<int:pk>/supprimer/',     views.partenaire_bourse_delete, name='partenaire_bourse_delete'),
    path('annuel/',                  views.honoraires_annuels,    name='honoraires_annuels'),
    path('honoraire/<int:pk>/modifier/',   views.honoraire_edit,   name='honoraire_edit'),
    path('honoraire/<int:pk>/supprimer/',  views.honoraire_delete, name='honoraire_delete'),
    path('export/excel/',            views.export_excel,          name='export_excel'),
    path('export/pdf/',              views.export_pdf,            name='export_pdf'),
    path('export/word/',             views.export_word,           name='export_word'),
    path('export/teacher/excel/',    views.export_teacher_excel,  name='export_teacher_excel'),
    path('export/teacher/pdf/',      views.export_teacher_pdf,    name='export_teacher_pdf'),
    path('export/teacher/word/',     views.export_teacher_word,   name='export_teacher_word'),
    path('annuel/export/excel/',     views.export_annuel_excel,   name='export_annuel_excel'),
    path('annuel/export/pdf/',       views.export_annuel_pdf,     name='export_annuel_pdf'),
    path('annuel/export/word/',      views.export_annuel_word,    name='export_annuel_word'),
    # Validation Inscription
    path('inscriptions/',                      views.validation_inscription_list,   name='validation_inscription_list'),
    path('inscriptions/nouvelle/',             views.validation_inscription_create, name='validation_inscription_create'),
    path('inscriptions/<int:pk>/',             views.validation_inscription_detail, name='validation_inscription_detail'),
    path('inscriptions/<int:pk>/supprimer/',   views.validation_inscription_delete, name='validation_inscription_delete'),
    path('preuves-paiement/',                  views.payment_proof_list,   name='payment_proof_list'),
    path('preuves-paiement/<int:pk>/',         views.payment_proof_detail, name='payment_proof_detail'),
    path('inscriptions/<int:pk>/paiement/',    views.enrollment_update_payment,     name='enrollment_update_payment'),
    path('inscriptions/<int:pk>/certificat/',  views.certificat_inscription_pdf,    name='certificat_inscription_pdf'),
    path('inscriptions/<int:pk>/attestation/', views.attestation_passage_pdf,       name='attestation_passage_pdf'),
    # Attestation de réussite
    path('inscriptions/<int:pk>/reussite/',    views.attestation_reussite_pdf,      name='attestation_reussite_pdf'),
    # État journalier : modifier / supprimer une ligne
    path('etat/caisse/<int:pk>/modifier/',     views.etat_caisse_edit,              name='etat_caisse_edit'),
    path('etat/caisse/<int:pk>/supprimer/',    views.etat_caisse_delete,            name='etat_caisse_delete'),
    path('etat/installment/<int:pk>/modifier/',views.etat_installment_edit,         name='etat_installment_edit'),
    path('etat/installment/<int:pk>/supprimer/',views.etat_installment_delete,      name='etat_installment_delete'),
    # État journalier & clôture
    path('etat/',                              views.etat_journalier,               name='etat_journalier'),
    path('etat/pdf/',                          views.etat_journalier_pdf,           name='etat_journalier_pdf'),
    path('etat/excel/',                        views.etat_journalier_excel,         name='etat_journalier_excel'),
    path('etat/word/',                         views.etat_journalier_word,          name='etat_journalier_word'),
    path('etat/cloturer/',                     views.cloturer_journee,              name='cloturer_journee'),
    path('clotures/',                          views.clotures_list,                 name='clotures_list'),
    path('clotures/<int:pk>/modifier/',        views.closure_edit,                  name='closure_edit'),
    path('clotures/<int:pk>/supprimer/',       views.closure_delete,                name='closure_delete'),
    path('clotures/email-config/',             views.closure_email_config_view,     name='closure_email_config'),
    # Entrée & Sortie Caisse (mouvements de caisse — Brouillard)
    path('mouvements-caisse/',                          views.caisse_movement_list,       name='caisse_movement_list'),
    path('mouvements-caisse/creer/',                    views.caisse_movement_create,     name='caisse_movement_create'),
    path('mouvements-caisse/<int:pk>/decaisser/',       views.caisse_movement_decaisser,  name='caisse_movement_decaisser'),
    path('mouvements-caisse/<int:pk>/modifier/',        views.caisse_movement_edit,       name='caisse_movement_edit'),
    path('mouvements-caisse/<int:pk>/supprimer/',       views.caisse_movement_delete,     name='caisse_movement_delete'),
    # Fiche des dépenses (reçu de mouvement de caisse imprimable)
    path('fiche-depense/<int:pk>/',                     views.fiche_depense_detail,       name='fiche_depense_detail'),
    path('fiche-depense/<int:pk>/pdf/',                 views.fiche_depense_pdf,          name='fiche_depense_pdf'),
    # Demandes de dépense par Direction (soumission -> validation TG -> décaissement Caisse)
    path('demandes-depense/',                           views.demande_depense_list,       name='demande_depense_list'),
    path('demandes-depense/creer/',                     views.demande_depense_create,     name='demande_depense_create'),
    path('demandes-depense/<int:pk>/',                  views.demande_depense_detail,     name='demande_depense_detail'),
    path('demandes-depense/<int:pk>/pdf/',              views.demande_depense_pdf,        name='demande_depense_pdf'),
    path('demandes-depense/<int:pk>/modifier/',         views.demande_depense_edit,       name='demande_depense_edit'),
    path('demandes-depense/<int:pk>/supprimer/',        views.demande_depense_delete,     name='demande_depense_delete'),
    path('demandes-depense/<int:pk>/valider/',          views.demande_depense_valider,    name='demande_depense_valider'),
    path('demandes-depense/<int:pk>/rejeter/',          views.demande_depense_rejeter,    name='demande_depense_rejeter'),
    path('demandes-depense/<int:pk>/decaisser/',        views.demande_depense_decaisser,  name='demande_depense_decaisser'),
    # Rapports financiers (Direction Administrative Financière)
    path('rapports-financiers/',                        views.rapports_financiers,             name='rapports_financiers'),
    path('rapports-financiers/export/excel/',            views.rapports_financiers_export_excel, name='rapports_financiers_export_excel'),
    path('rapports-financiers/export/pdf/',              views.rapports_financiers_export_pdf,   name='rapports_financiers_export_pdf'),
    path('rapports-financiers/export/word/',             views.rapports_financiers_export_word,  name='rapports_financiers_export_word'),
    # Comptes comptables (plan comptable — Trésorier Général)
    path('comptes-comptables/',                         views.compte_comptable_list,      name='compte_comptable_list'),
    path('comptes-comptables/creer/',                   views.compte_comptable_create,    name='compte_comptable_create'),
    path('comptes-comptables/<int:pk>/modifier/',       views.compte_comptable_edit,      name='compte_comptable_edit'),
    path('comptes-comptables/<int:pk>/supprimer/',      views.compte_comptable_delete,    name='compte_comptable_delete'),
    path('comptes-comptables/<int:pk>/toggle/',         views.compte_comptable_toggle,    name='compte_comptable_toggle'),
    path('students/<int:pk>/fin-de-cycle/',             views.attestation_fin_cycle_pdf,  name='attestation_fin_cycle_pdf'),
    # Liste étudiants (financière + inscriptions)
    path('etudiants/',                         views.financial_student_list,         name='financial_student_list'),
    path('etudiants/pdf/',                     views.financial_student_list_pdf,     name='financial_student_list_pdf'),
    path('etudiants/word/',                    views.financial_student_list_word,    name='financial_student_list_word'),
    # Portail étudiant
    path('mon-certificat/',                    views.mon_certificat_inscription_pdf, name='mon_certificat_inscription_pdf'),
    path('mon-attestation-passage/',           views.mon_attestation_passage_pdf,    name='mon_attestation_passage_pdf'),
    path('supplement-diplome/<str:cycle>/',    views.diploma_supplement_pdf,         name='diploma_supplement_pdf'),
    path('attestation-non-soutenance/',        views.attestation_non_soutenance_pdf, name='attestation_non_soutenance_pdf'),
    # Répartition Année Académique
    path('repartition/',                       views.repartition_annee_list,        name='repartition_annee_list'),
    path('repartition/nouvelle/',              views.repartition_annee_create,      name='repartition_annee_create'),
    path('repartition/<int:pk>/modifier/',     views.repartition_annee_edit,        name='repartition_annee_edit'),
    path('repartition/<int:pk>/supprimer/',    views.repartition_annee_delete,      name='repartition_annee_delete'),
    # Paiement mensualités
    path('mensualites/',                       views.mensualite_list,               name='mensualite_list'),
    path('mensualites/classe/modifier/',       views.mensualite_update_class_fee,   name='mensualite_update_class_fee'),
    path('mensualites/<int:enrollment_pk>/soutenance/', views.mensualite_update_soutenance, name='mensualite_update_soutenance'),
    path('mensualites/<int:enrollment_pk>/payer/', views.mensualite_payer,          name='mensualite_payer'),
    path('mensualites/<int:enrollment_pk>/recu/<int:year>/<int:month>/', views.mensualite_recu_pdf, name='mensualite_recu_pdf'),
    # Taux de recouvrement
    path('recouvrement/',                      views.taux_recouvrement,             name='taux_recouvrement'),
    # Suivi des boursiers (régularisation avec les partenaires)
    path('boursiers/',                         views.boursier_list,                 name='boursier_list'),
    path('boursiers/<int:pk>/',                views.boursier_update,               name='boursier_update'),
    path('boursiers/<int:pk>/attestation/pdf/',  views.boursier_attestation_pdf,     name='boursier_attestation_pdf'),
    path('boursiers/<int:pk>/attestation/word/', views.boursier_attestation_word,    name='boursier_attestation_word'),
    # Reçu d'inscription
    path('inscriptions/<int:pk>/recu/',        views.inscription_recu,              name='inscription_recu'),
    path('inscriptions/<int:pk>/recu/pdf/',    views.inscription_recu_pdf,          name='inscription_recu_pdf'),
    # La Caisse
    path('caisse/',                            views.caisse_dashboard,              name='caisse_dashboard'),
    path('caisse/nouveau/',                    views.caisse_payment_create,         name='caisse_payment_create'),
    path('caisse/<int:pk>/recu/',              views.caisse_recu_pdf,               name='caisse_recu_pdf'),
    path('caisse/recherche-etudiant/',         views.caisse_student_search,         name='caisse_student_search'),
    path('caisse/etudiant/<int:pk>/frais/',    views.caisse_student_fees,           name='caisse_student_fees'),
    path('attestations-passage/',              views.attestation_passage_list,      name='attestation_passage_list'),
    # Gestion frais Soutenance (Licence 3 / Master 2)
    path('soutenance/',                              views.soutenance_dashboard,         name='soutenance_dashboard'),
    path('soutenance/recherche-etudiant/',           views.soutenance_student_search,    name='soutenance_student_search'),
    path('soutenance/inscription/<int:enrollment_pk>/frais/', views.soutenance_enrollment_fees, name='soutenance_enrollment_fees'),
    path('soutenance/<int:enrollment_pk>/valider/',  views.soutenance_payer,              name='soutenance_payer'),

    # Pilotage et Suivi Budgétaire (Contrôleur Interne / Administrateur d'institut / DAF)
    path('budget/',                                   budget_views.budget_dashboard,          name='budget_dashboard'),
    path('budget/bsc/',                               budget_views.bsc_dashboard,             name='bsc_dashboard'),
    path('budget/sources/',                           budget_views.source_financement_list,   name='source_financement_list'),
    path('budget/sources/creer/',                     budget_views.source_financement_create, name='source_financement_create'),
    path('budget/sources/<int:pk>/modifier/',         budget_views.source_financement_edit,   name='source_financement_edit'),
    path('budget/sources/<int:pk>/supprimer/',        budget_views.source_financement_delete, name='source_financement_delete'),
    path('budget/lignes/',                            budget_views.ligne_budgetaire_list,     name='ligne_budgetaire_list'),
    path('budget/lignes/creer/',                      budget_views.ligne_budgetaire_create,   name='ligne_budgetaire_create'),
    path('budget/lignes/<int:pk>/',                   budget_views.ligne_budgetaire_detail,   name='ligne_budgetaire_detail'),
    path('budget/lignes/<int:pk>/modifier/',          budget_views.ligne_budgetaire_edit,     name='ligne_budgetaire_edit'),
    path('budget/suivi-directions/',                  budget_views.suivi_budget_directions,        name='suivi_budget_directions'),
    path('budget/suivi-directions/<int:pk>/',         budget_views.suivi_budget_direction_detail,  name='suivi_budget_direction_detail'),
    path('budget/rectificatifs/',                     budget_views.rectificatif_list,         name='rectificatif_list'),
    path('budget/rectificatifs/creer/',               budget_views.rectificatif_create,       name='rectificatif_create'),
    path('budget/rectificatifs/<int:pk>/valider/',    budget_views.rectificatif_valider,      name='rectificatif_valider'),
    path('budget/rectificatifs/<int:pk>/rejeter/',    budget_views.rectificatif_rejeter,      name='rectificatif_rejeter'),
    path('budget/engagements/',                       budget_views.engagement_list,           name='engagement_list'),
    path('budget/engagements/creer/',                 budget_views.engagement_create,         name='engagement_create'),
    path('budget/engagements/<int:pk>/soumettre/',    budget_views.engagement_soumettre,      name='engagement_soumettre'),
    path('budget/engagements/<int:pk>/valider/',      budget_views.engagement_valider,        name='engagement_valider'),
    path('budget/engagements/<int:pk>/rejeter/',      budget_views.engagement_rejeter,        name='engagement_rejeter'),
    path('budget/engagements/<int:pk>/annuler/',      budget_views.engagement_annuler,        name='engagement_annuler'),
]
