# Generated by Django 5.1.4 on 2026-06-17 16:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_structure", "0004_student_extended_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HourlyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Taux horaire (FCFA/heure)",
                    ),
                ),
                (
                    "hours_per_session",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        max_digits=4,
                        verbose_name="Heures par séance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_rates",
                        to="academic_structure.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hourly_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_rates",
                        to="academic_structure.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_rates",
                        to="academic_structure.level",
                        verbose_name="Niveau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taux horaire",
                "verbose_name_plural": "Taux horaires",
                "db_table": "hourly_rates",
                "ordering": ["department", "level"],
                "unique_together": {("department", "level", "academic_year")},
            },
        ),
    ]
