# Generated by Django 5.1.4 on 2026-06-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hourlyrate",
            name="hours_per_session",
        ),
    ]
