# Generated by Django 5.1.4 on 2026-06-18 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0004_student_extended_fields"),
        ("accounting", "0002_remove_hours_per_session"),
        ("attendance", "0003_add_signed_by_admin"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherHonoraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField(verbose_name="Date de la séance")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Durée (heures)"
                    ),
                ),
                (
                    "rate_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Taux horaire (FCFA/h)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant (FCFA)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraires",
                        to="academic_structure.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "attendance_sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraire",
                        to="attendance.attendancesheet",
                        verbose_name="Feuille d'émargement",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraires",
                        to="academic_structure.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraires",
                        to="teachers.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_honoraires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Honoraire enseignant",
                "verbose_name_plural": "Honoraires enseignants",
                "db_table": "teacher_honoraires",
                "ordering": ["-session_date"],
            },
        ),
    ]
