# Generated by Django 5.1.4 on 2026-06-19 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0006_add_bulletin_config"),
        ("accounting", "0003_add_teacher_honoraire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYearDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nb_months",
                    models.PositiveSmallIntegerField(
                        help_text="Nombre de mois de l'année académique attribués à cette classe",
                        verbose_name="Nombre de mois",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observations")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="academic_structure.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_distribution",
                        to="academic_structure.class",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_distributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Répartition année académique",
                "verbose_name_plural": "Répartitions années académiques",
                "db_table": "academic_year_distributions",
                "ordering": ["academic_year", "class_group__name"],
                "unique_together": {("academic_year", "class_group")},
            },
        ),
    ]
