# Generated by Django 5.1.4 on 2026-06-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_academicyeardistribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyeardistribution",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Janvier"),
                    (2, "Février"),
                    (3, "Mars"),
                    (4, "Avril"),
                    (5, "Mai"),
                    (6, "Juin"),
                    (7, "Juillet"),
                    (8, "Août"),
                    (9, "Septembre"),
                    (10, "Octobre"),
                    (11, "Novembre"),
                    (12, "Décembre"),
                ],
                default=9,
                help_text="Premier mois de l'année académique pour cette classe",
                verbose_name="Mois de début",
            ),
        ),
    ]
