# Generated by Django 5.1.4 on 2026-06-19 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_add_start_month_to_distribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComptabiliteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frais_generaux",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant soustrait automatiquement des frais totaux à chaque inscription",
                        max_digits=12,
                        verbose_name="Frais généraux (FCFA)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comptabilite_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration comptable",
                "db_table": "comptabilite_config",
            },
        ),
    ]
