# Generated by Django 5.1.4 on 2026-06-19 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0006_add_bulletin_config"),
        ("accounting", "0006_add_frais_generaux"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "closure_date",
                    models.DateField(unique=True, verbose_name="Date de clôture"),
                ),
                (
                    "nb_validated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Inscriptions validées"
                    ),
                ),
                (
                    "nb_pending",
                    models.PositiveIntegerField(default=0, verbose_name="En attente"),
                ),
                (
                    "nb_rejected",
                    models.PositiveIntegerField(default=0, verbose_name="Rejetées"),
                ),
                (
                    "nb_suspended",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Comptes suspendus"
                    ),
                ),
                (
                    "total_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total encaissé (FCFA)",
                    ),
                ),
                (
                    "total_installments",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Mensualités encaissées (FCFA)",
                    ),
                ),
                (
                    "total_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total restant dû (FCFA)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observations")),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closures",
                        to="academic_structure.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Clôturé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clôture comptable",
                "verbose_name_plural": "Clôtures comptables",
                "db_table": "accounting_closures",
                "ordering": ["-closure_date"],
            },
        ),
    ]
