# Generated by Django 5.1.4 on 2026-06-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_add_frais_generaux_niveau"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraisgenerauxniveau",
            name="frais_totaux",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant total des frais d'inscription pour ce niveau",
                max_digits=12,
                null=True,
                verbose_name="Frais totaux d'inscription (FCFA)",
            ),
        ),
    ]
