# Generated by Django 5.1.4 on 2026-06-20 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0006_add_bulletin_config"),
        ("accounting", "0009_add_frais_totaux_to_niveau"),
        ("students", "0006_add_frais_generaux"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaissePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="Référence reçu",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("INSCRIPTION", "Frais d'inscription"),
                            ("SCOLARITE", "Frais de scolarité"),
                            ("SOUTENANCE", "Frais de soutenance"),
                        ],
                        max_length=20,
                        verbose_name="Type de frais",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant (FCFA)"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Date de paiement")),
                ("notes", models.TextField(blank=True, verbose_name="Observations")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisse_payments",
                        to="academic_structure.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisse_payments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caisse_payments",
                        to="students.student",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement caisse",
                "verbose_name_plural": "Paiements caisse",
                "db_table": "caisse_payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
