# Generated by Django 5.1.4 on 2026-06-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_caisse_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraisgenerauxniveau",
            name="frais_mensuel",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant mensuel de scolarité à payer pour ce niveau",
                max_digits=12,
                null=True,
                verbose_name="Mensualité scolarité (FCFA)",
            ),
        ),
    ]
