# Generated by Django 5.1.4 on 2026-06-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_frais_mensuel_niveau"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissepayment",
            name="payment_month",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Numéro du mois (1-12), uniquement pour les frais de scolarité",
                null=True,
                verbose_name="Mois concerné",
            ),
        ),
    ]
