# Generated by Django 5.1.4 on 2026-06-20 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0007_institut_config"),
        ("accounting", "0012_caisse_payment_month"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraisMensuelClasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frais_mensuel",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant mensuel dû pour cette classe",
                        max_digits=12,
                        verbose_name="Mensualité scolarité (FCFA)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frais_mensuel_config",
                        to="academic_structure.class",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frais_mensuel_classe_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensualité par classe",
                "verbose_name_plural": "Mensualités par classe",
                "db_table": "frais_mensuel_classe",
                "ordering": ["class_group__level__name", "class_group__name"],
            },
        ),
    ]
