# Generated by Django 5.1.4 on 2026-06-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0014_fix_cross_db_fk_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosureEmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        blank=True,
                        help_text="Chaque ligne = une adresse e-mail qui recevra le rapport de clôture.",
                        verbose_name="Adresses e-mail (une par ligne)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Config e-mail clôture",
                "db_table": "accounting_closure_email_config",
            },
        ),
    ]
