# Generated by Django 5.1.4 on 2026-06-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_closure_email_config"),
        ("students", "0009_add_pending_caisse_advance_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissepayment",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caisse_payments",
                to="students.enrollment",
                verbose_name="Inscription liée",
            ),
        ),
    ]
