# Generated by Django 5.1.4 on 2026-06-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_add_enrollment_fk_to_caisse_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissepayment",
            name="payment_months",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Liste de numéros de mois séparés par virgule, ex: 10,11,12,6",
                max_length=100,
                verbose_name="Mois payés",
            ),
        ),
    ]
