# Generated by Django 5.1.4 on 2026-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0018_partenairebourse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fraismensuelclasse",
            options={
                "ordering": ["class_group__level__name", "class_group__name"],
                "verbose_name": "Frais par classe",
                "verbose_name_plural": "Frais par classe",
            },
        ),
        migrations.AddField(
            model_name="fraismensuelclasse",
            name="frais_amea",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais AMEA (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="fraismensuelclasse",
            name="frais_assurance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais d'assurance (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="fraismensuelclasse",
            name="frais_bibliotheque",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais Bibliothèque (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="fraismensuelclasse",
            name="frais_tenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais de tenue (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="fraismensuelclasse",
            name="montant_global",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Coût total de la formation pour cette classe",
                max_digits=12,
                null=True,
                verbose_name="Montant global de la formation (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="fraismensuelclasse",
            name="frais_mensuel",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant mensuel dû pour cette classe",
                max_digits=12,
                null=True,
                verbose_name="Mensualité scolarité (FCFA)",
            ),
        ),
    ]
