# Generated by Django 5.1.4 on 2026-07-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0019_alter_fraismensuelclasse_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraismensuelclasse",
            name="frais_soutenance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applicable en Licence 3 et Master 2. Pré-rempli automatiquement (60 000 FCFA en L3, 100 000 FCFA en M2), modifiable.",
                max_digits=12,
                null=True,
                verbose_name="Frais de soutenance normal (FCFA)",
            ),
        ),
    ]
