# Generated by Django 5.1.4 on 2026-07-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_alter_fraismensuelclasse_frais_amea"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraismensuelclasse",
            name="frais_inscription",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Utilisé pour calculer le droit d'inscription lors de la validation d'inscription",
                max_digits=12,
                null=True,
                verbose_name="Frais d'inscription (FCFA)",
            ),
        ),
    ]
