# Generated by Django 5.1.4 on 2026-07-05 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_fraismensuelclasse_frais_inscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingclosure",
            name="total_entrees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Total entrées de caisse (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="accountingclosure",
            name="total_sorties",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                verbose_name="Total sorties de caisse (FCFA)",
            ),
        ),
        migrations.CreateModel(
            name="CaisseMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("ENTREE", "Entrée"), ("SORTIE", "Sortie")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant (FCFA)"
                    ),
                ),
                ("movement_date", models.DateField(verbose_name="Date")),
                ("motif", models.CharField(max_length=255, verbose_name="Motif")),
                ("notes", models.TextField(blank=True, verbose_name="Observations")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_executed",
                    models.BooleanField(
                        default=False, verbose_name="Exécuté (décaissé)"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Décaissé le"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisse_movements_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Saisi par (Trésorier Général)",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisse_movements_executes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Décaissé par (Caissier)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de caisse",
                "verbose_name_plural": "Mouvements de caisse",
                "db_table": "caisse_movements",
                "ordering": ["-movement_date", "-created_at"],
            },
        ),
    ]
