# Generated by Django 5.1.4 on 2026-07-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0024_accountingclosure_total_entrees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissemovement",
            name="beneficiaire",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Bénéficiaire / Fournisseur"
            ),
        ),
        migrations.AddField(
            model_name="caissemovement",
            name="categorie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOURNITURES", "Fournitures de bureau"),
                    ("ENTRETIEN", "Entretien & maintenance"),
                    ("TRANSPORT", "Transport & mission"),
                    ("COMMUNICATION", "Communication & téléphone"),
                    ("BANCAIRE", "Frais bancaires"),
                    ("RESTAURATION", "Restauration"),
                    ("AUTRE", "Autre"),
                ],
                max_length=20,
                verbose_name="Catégorie de dépense",
            ),
        ),
        migrations.AddField(
            model_name="caissemovement",
            name="piece_justificative",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Pièce justificative (référence)",
            ),
        ),
    ]
