# Generated by Django 5.1.4 on 2026-07-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0026_comptecomptable"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissemovement",
            name="compte_associe",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_associes",
                to="accounting.comptecomptable",
                verbose_name="Compte associé",
            ),
        ),
        migrations.AddField(
            model_name="caissemovement",
            name="compte_caisse",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvements_caisse",
                to="accounting.comptecomptable",
                verbose_name="N° compte (caisse / banque)",
            ),
        ),
        migrations.AddField(
            model_name="caissemovement",
            name="justificatif",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="caisse_justificatifs/%Y/%m/",
                verbose_name="Justificatif (pièce scannée)",
            ),
        ),
        migrations.AddField(
            model_name="comptecomptable",
            name="categorie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOURNITURES", "Fournitures de bureau"),
                    ("ENTRETIEN", "Entretien & maintenance"),
                    ("TRANSPORT", "Transport & mission"),
                    ("COMMUNICATION", "Communication & téléphone"),
                    ("BANCAIRE", "Frais bancaires"),
                    ("RESTAURATION", "Restauration"),
                    ("AUTRE", "Autre"),
                ],
                help_text="Suggestion automatique de ce compte lorsque cette catégorie de dépense est choisie sur une Sortie.",
                max_length=20,
                verbose_name="Catégorie de dépense associée",
            ),
        ),
        migrations.AddField(
            model_name="comptecomptable",
            name="classe",
            field=models.CharField(
                choices=[
                    ("1", "Classe 1 — Comptes de ressources durables"),
                    ("2", "Classe 2 — Comptes d’actif immobilisé"),
                    ("3", "Classe 3 — Comptes de stocks"),
                    ("4", "Classe 4 — Comptes de tiers"),
                    ("5", "Classe 5 — Comptes de trésorerie"),
                    ("6", "Classe 6 — Comptes de charges"),
                    ("7", "Classe 7 — Comptes de produits"),
                    ("8", "Classe 8 — Autres charges / produits (HAO)"),
                ],
                default="5",
                max_length=1,
                verbose_name="Classe SYSCOHADA",
            ),
        ),
        migrations.AddField(
            model_name="comptecomptable",
            name="nature",
            field=models.CharField(
                choices=[
                    ("TRESORERIE", "Trésorerie (caisse / banque)"),
                    ("TIERS", "Tiers (clients, fournisseurs…)"),
                    ("PRODUIT", "Produit (recette)"),
                    ("CHARGE", "Charge (dépense)"),
                ],
                default="TRESORERIE",
                max_length=12,
                verbose_name="Nature du compte",
            ),
        ),
        migrations.AddField(
            model_name="comptecomptable",
            name="sens",
            field=models.CharField(
                choices=[
                    ("ENTREE", "Entrée uniquement"),
                    ("SORTIE", "Sortie uniquement"),
                    ("MIXTE", "Entrée et Sortie"),
                ],
                default="MIXTE",
                max_length=6,
                verbose_name="Sens (nature de l’opération)",
            ),
        ),
    ]
