# Generated by Django 5.1.4 on 2026-07-05 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0027_caissemovement_compte_associe_and_more"),
        ("accounts", "0024_alter_role_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeDepense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        unique=True,
                        verbose_name="N° de référence",
                    ),
                ),
                (
                    "objet",
                    models.CharField(
                        max_length=255, verbose_name="Objet de la demande"
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FOURNITURES", "Fournitures de bureau"),
                            ("ENTRETIEN", "Entretien & maintenance"),
                            ("TRANSPORT", "Transport & mission"),
                            ("COMMUNICATION", "Communication & téléphone"),
                            ("BANCAIRE", "Frais bancaires"),
                            ("RESTAURATION", "Restauration"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie de dépense",
                    ),
                ),
                (
                    "motif",
                    models.TextField(verbose_name="Motif / Description de la dépense"),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "ordonnateur",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Ordonnateur"
                    ),
                ),
                (
                    "fournisseur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Fournisseur"
                    ),
                ),
                (
                    "beneficiaire",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bénéficiaire"
                    ),
                ),
                (
                    "piece_justificative",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Pièce justificative (référence)",
                    ),
                ),
                (
                    "justificatif",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="demandes_depense/%Y/%m/",
                        verbose_name="Justificatif",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente de validation"),
                            ("VALIDEE", "Validée — en attente de décaissement"),
                            ("REJETEE", "Rejetée"),
                            ("DECAISSEE", "Décaissée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                        verbose_name="Statut",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif du rejet"),
                ),
                ("decaisse_at", models.DateTimeField(blank=True, null=True)),
                (
                    "caisse_movement",
                    models.OneToOneField(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demande_depense",
                        to="accounting.caissemovement",
                        verbose_name="Mouvement de caisse généré",
                    ),
                ),
                (
                    "decaisse_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_depense_decaissees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Décaissée par (Caissier)",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_depense",
                        to="accounts.direction",
                        verbose_name="Direction",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_depense_soumises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Soumise par",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_depense_validees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validée par (Trésorier Général)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de dépense",
                "verbose_name_plural": "Demandes de dépense",
                "db_table": "demandes_depense",
                "ordering": ["-requested_at"],
            },
        ),
    ]
