# Generated by Django 5.1.4 on 2026-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0029_alter_caissemovement_categorie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissepayment",
            name="soutenance_type",
            field=models.CharField(
                blank=True,
                choices=[("NORMALE", "Normale"), ("SPECIALE", "Spéciale")],
                help_text="Uniquement pour les frais de soutenance : normale ou spéciale.",
                max_length=10,
                verbose_name="Type de soutenance",
            ),
        ),
    ]
