# Generated by Django 5.1.4 on 2026-07-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0019_institutconfig_contrat_article1_texte_and_more"),
        ("accounting", "0030_caissepayment_soutenance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissemovement",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caisse_movements",
                to="academic_structure.academicyear",
                verbose_name="Année académique",
            ),
        ),
    ]
