# Generated by Django 5.1.4 on 2026-07-18 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0022_institutdisabledfeature_institutdisabledtab"),
        ("accounting", "0031_caissemovement_academic_year"),
        ("accounts", "0032_controllerinstitut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comptabiliteconfig",
            name="budget_seuil_orange",
            field=models.DecimalField(
                decimal_places=2,
                default=0.8,
                max_digits=4,
                verbose_name="Seuil d'alerte orange (taux d'exécution budgétaire)",
            ),
        ),
        migrations.AddField(
            model_name="comptabiliteconfig",
            name="budget_seuil_rouge",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=4,
                verbose_name="Seuil d'alerte rouge (taux d'exécution budgétaire)",
            ),
        ),
        migrations.CreateModel(
            name="LigneBudgetaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("FONCTIONNEMENT", "Fonctionnement"),
                            ("INVESTISSEMENT", "Investissement"),
                        ],
                        default="FONCTIONNEMENT",
                        max_length=20,
                        verbose_name="Nature",
                    ),
                ),
                (
                    "montant_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Montant initial (FCFA)",
                    ),
                ),
                (
                    "montant_revise",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Montant révisé (FCFA)",
                    ),
                ),
                (
                    "montant_engage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="Montant engagé (FCFA)",
                    ),
                ),
                (
                    "montant_execute",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="Montant exécuté (FCFA)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_budgetaires",
                        to="academic_structure.academicyear",
                        verbose_name="Exercice (année académique)",
                    ),
                ),
                (
                    "compte_comptable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_budgetaires",
                        to="accounting.comptecomptable",
                        verbose_name="Compte comptable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lignes_budgetaires_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_budgetaires",
                        to="accounts.direction",
                        verbose_name="Direction (centre de coût)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne budgétaire",
                "verbose_name_plural": "Lignes budgétaires",
                "db_table": "budget_lignes",
                "ordering": ["-academic_year__start_date", "direction"],
            },
        ),
        migrations.CreateModel(
            name="EngagementBudgetaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                ("objet", models.CharField(max_length=255, verbose_name="Objet")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "date_engagement",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'engagement",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("SOUMIS", "Soumis"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "piece_justificative",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="budget/engagements/%Y/%m/",
                        verbose_name="Pièce justificative",
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif du rejet"),
                ),
                (
                    "demandeur",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engagements_budgetaires_demandes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engagements_budgetaires_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "ligne_budgetaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engagements",
                        to="accounting.lignebudgetaire",
                        verbose_name="Ligne budgétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement budgétaire",
                "verbose_name_plural": "Engagements budgétaires",
                "db_table": "budget_engagements",
                "ordering": ["-date_engagement"],
            },
        ),
        migrations.CreateModel(
            name="BudgetRectificatif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_ajustement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positif pour augmenter le budget, négatif pour le réduire.",
                        max_digits=14,
                        verbose_name="Montant d'ajustement (FCFA)",
                    ),
                ),
                ("motif", models.TextField(verbose_name="Motif")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DEMANDE", "Demandé"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="DEMANDE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("demande_at", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif du rejet"),
                ),
                (
                    "demande_par",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rectificatifs_demandes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandé par",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rectificatifs_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "ligne_budgetaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rectificatifs",
                        to="accounting.lignebudgetaire",
                        verbose_name="Ligne budgétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget rectificatif",
                "verbose_name_plural": "Budgets rectificatifs",
                "db_table": "budget_rectificatifs",
                "ordering": ["-demande_at"],
            },
        ),
        migrations.AddField(
            model_name="demandedepense",
            name="ligne_budgetaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_depense",
                to="accounting.lignebudgetaire",
                verbose_name="Ligne budgétaire",
            ),
        ),
        migrations.CreateModel(
            name="SourceFinancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "type_source",
                    models.CharField(
                        choices=[
                            ("ETAT", "État"),
                            ("FRAIS_SCOLARITE", "Frais de scolarité"),
                            ("SUBVENTION", "Subvention"),
                            ("PARTENARIAT", "Partenariat"),
                            ("DON", "Don"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de source",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sources_financement_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Source de financement",
                "verbose_name_plural": "Sources de financement",
                "db_table": "budget_sources_financement",
                "ordering": ["libelle"],
            },
        ),
        migrations.AddField(
            model_name="lignebudgetaire",
            name="source_financement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_budgetaires",
                to="accounting.sourcefinancement",
                verbose_name="Source de financement",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lignebudgetaire",
            unique_together={
                ("academic_year", "direction", "compte_comptable", "source_financement")
            },
        ),
    ]
