# Generated by Django 5.1.4 on 2026-07-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0032_comptabiliteconfig_budget_seuil_orange_and_more"),
        ("strategic_plan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignebudgetaire",
            name="axe_strategique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lignes_budgetaires",
                to="strategic_plan.axestrategique",
                verbose_name="Axe stratégique",
            ),
        ),
        migrations.AddField(
            model_name="lignebudgetaire",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lignes_budgetaires",
                to="strategic_plan.projet",
                verbose_name="Projet",
            ),
        ),
    ]
