# Generated by Django 5.1.4 on 2026-07-22 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0033_lignebudgetaire_axe_strategique_and_more"),
        ("students", "0017_student_class_rep_by_student_class_rep_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moyen_paiement",
                    models.CharField(
                        choices=[
                            ("WAVE", "Wave"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("VISA", "Carte bancaire (VISA)"),
                            ("VIREMENT", "Virement bancaire"),
                        ],
                        max_length=15,
                        verbose_name="Moyen de paiement",
                    ),
                ),
                (
                    "montant_declare",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant déclaré (FCFA)",
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "piece_justificative",
                    models.FileField(
                        upload_to="admissions/justificatifs/%Y/%m/",
                        verbose_name="Reçu / capture d'écran",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Déposé le"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("VALIDATED", "Validé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_proofs",
                        to="students.enrollment",
                        verbose_name="Inscription",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_proofs_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preuve de paiement",
                "verbose_name_plural": "Preuves de paiement",
                "db_table": "payment_proofs",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
