# Generated by Django 5.1.4 on 2026-07-22 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0034_paymentproof"),
        ("students", "0017_student_class_rep_by_student_class_rep_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlinePaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("PAYDUNYA", "PayDunya")],
                        default="PAYDUNYA",
                        max_length=20,
                        verbose_name="Agrégateur",
                    ),
                ),
                (
                    "invoice_token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Jeton de la facture"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Renseigné par l'agrégateur à la confirmation (Wave, Orange Money, carte…).",
                        max_length=30,
                        verbose_name="Moyen utilisé",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("COMPLETED", "Confirmé"),
                            ("FAILED", "Échoué / annulé"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(
                        blank=True,
                        help_text="Conservée à des fins de diagnostic/audit.",
                        verbose_name="Réponse brute de l'agrégateur",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_payment_transactions",
                        to="students.enrollment",
                        verbose_name="Inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction de paiement en ligne",
                "verbose_name_plural": "Transactions de paiement en ligne",
                "db_table": "online_payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
