# Generated by Django 5.1.4 on 2026-07-23 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0035_onlinepaymenttransaction"),
        ("accounts", "0039_alter_role_name_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caissemovement",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caisse_movements",
                to="accounts.direction",
                verbose_name="Direction (centre de coût)",
            ),
        ),
    ]
