# Generated by Django 5.1.4 on 2026-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0036_caissemovement_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlinepaymenttransaction",
            name="invoice_token",
            field=models.CharField(
                help_text="Identifiant de session Wave (checkout session id) ou pay_token Orange Money.",
                max_length=100,
                unique=True,
                verbose_name="Jeton de la transaction",
            ),
        ),
        migrations.AlterField(
            model_name="onlinepaymenttransaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                help_text="Détail renseigné par le fournisseur à la confirmation (ex. numéro de mobile money).",
                max_length=30,
                verbose_name="Moyen utilisé",
            ),
        ),
        migrations.AlterField(
            model_name="onlinepaymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[("WAVE", "Wave"), ("ORANGE_MONEY", "Orange Money")],
                max_length=20,
                verbose_name="Fournisseur",
            ),
        ),
    ]
