# Generated by Django 5.1.4 on 2026-07-29 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0030_remove_institutpaymentconfig_is_active_and_more"),
        ("accounting", "0037_alter_onlinepaymenttransaction_invoice_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HonoraireBudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vha",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Volume horaire annuel budgété",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraire_budget_lines",
                        to="academic_structure.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraire_budget_lines",
                        to="academic_structure.class",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_honoraire_budget_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honoraire_budget_lines",
                        to="academic_structure.department",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de budget honoraires",
                "verbose_name_plural": "Lignes de budget honoraires",
                "db_table": "honoraire_budget_lines",
                "ordering": ["class_group__level__order", "class_group__name"],
                "unique_together": {("department", "academic_year", "class_group")},
            },
        ),
        migrations.CreateModel(
            name="HonoraireBudgetMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        verbose_name="Année civile du mois"
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mai"),
                            (6, "Juin"),
                            (7, "Juillet"),
                            (8, "Août"),
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Décembre"),
                        ],
                        verbose_name="Mois",
                    ),
                ),
                (
                    "volume_heures",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="Volume horaire budgété",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="months",
                        to="accounting.honorairebudgetline",
                        verbose_name="Ligne de budget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mois de budget honoraires",
                "verbose_name_plural": "Mois de budget honoraires",
                "db_table": "honoraire_budget_months",
                "ordering": ["year", "month"],
                "unique_together": {("line", "year", "month")},
            },
        ),
    ]
