# Generated by Django 5.1.4 on 2026-07-18 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Risque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("financier", "Financier"),
                            ("operationnel", "Opérationnel"),
                            ("reputationnel", "Réputationnel"),
                            ("conformite", "Conformité"),
                            ("strategique", "Stratégique"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "gravite",
                    models.PositiveSmallIntegerField(verbose_name="Gravité (1-5)"),
                ),
                (
                    "probabilite",
                    models.PositiveSmallIntegerField(verbose_name="Probabilité (1-5)"),
                ),
                (
                    "plan_mitigation",
                    models.TextField(blank=True, verbose_name="Plan de mitigation"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("identifie", "Identifié"),
                            ("en_traitement", "En traitement"),
                            ("maitrise", "Maîtrisé"),
                            ("clos", "Clos"),
                        ],
                        default="identifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_identification",
                    models.DateField(verbose_name="Date d'identification"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risque",
                "verbose_name_plural": "Risques",
                "db_table": "risks_risques",
                "ordering": ["-gravite", "-probabilite"],
            },
        ),
        migrations.CreateModel(
            name="SuiviRisque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_suivi", models.DateField(verbose_name="Date de suivi")),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "nouveau_statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("identifie", "Identifié"),
                            ("en_traitement", "En traitement"),
                            ("maitrise", "Maîtrisé"),
                            ("clos", "Clos"),
                        ],
                        max_length=20,
                        verbose_name="Nouveau statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "risque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivis",
                        to="risks.risque",
                        verbose_name="Risque",
                    ),
                ),
                (
                    "suivi_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suivis_risques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Suivi par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi de risque",
                "verbose_name_plural": "Suivis de risque",
                "db_table": "risks_suivis",
                "ordering": ["-date_suivi"],
            },
        ),
        migrations.AddIndex(
            model_name="risque",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="risks_risqu_content_cb942a_idx",
            ),
        ),
    ]
