# Generated by Django 5.1.4 on 2026-06-16 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField(verbose_name="Date de la séance")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SIGNED", "Signé par l'enseignant"),
                            ("VALIDATED", "Validé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("teacher_signature_at", models.DateTimeField(blank=True, null=True)),
                ("teacher_comment", models.TextField(blank=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sheets",
                        to="timetable.timetableentry",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche d'émargement",
                "verbose_name_plural": "Fiches d'émargement",
                "db_table": "attendance_sheets",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Présent"),
                            ("ABSENT", "Absent"),
                            ("JUSTIFIED", "Absence justifiée"),
                            ("LATE", "Retard"),
                        ],
                        default="PRESENT",
                        max_length=15,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "justification_document",
                    models.FileField(
                        blank=True, null=True, upload_to="justifications/"
                    ),
                ),
                ("justified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendances",
                        to="attendance.attendancesheet",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence étudiant",
                "verbose_name_plural": "Présences étudiants",
                "db_table": "student_attendances",
            },
        ),
        migrations.AddIndex(
            model_name="attendancesheet",
            index=models.Index(
                fields=["timetable_entry", "session_date"],
                name="attendance__timetab_73c2e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesheet",
            index=models.Index(fields=["status"], name="attendance__status_1c585d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesheet",
            unique_together={("timetable_entry", "session_date")},
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["student", "status"], name="student_att_student_be1c2f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("attendance_sheet", "student")},
        ),
    ]
