# Generated by Django 5.1.4 on 2026-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesheet",
            name="lesson_content",
            field=models.TextField(
                blank=True,
                help_text="Décrivez le contenu dispensé (cahier de texte).",
                verbose_name="Contenu de la séance",
            ),
        ),
        migrations.AddField(
            model_name="attendancesheet",
            name="lesson_objectives",
            field=models.TextField(blank=True, verbose_name="Objectifs pédagogiques"),
        ),
    ]
