# Generated by Django 5.1.4 on 2026-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancesheet_lesson_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesheet",
            name="signed_by_admin",
            field=models.BooleanField(
                default=False,
                help_text="Vrai si c'est l'admin qui a signé à la place de l'enseignant.",
                verbose_name="Signé par l'administrateur",
            ),
        ),
    ]
