# Generated by Django 5.1.4 on 2026-06-18 13:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0004_student_extended_fields"),
        ("attendance", "0003_add_signed_by_admin"),
        ("subjects", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraSessionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif de la demande")),
                (
                    "extra_hours_requested",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Heures demandées"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "extra_hours_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Heures approuvées",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, verbose_name="Note de l'administrateur"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_requests",
                        to="academic_structure.academicyear",
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_requests",
                        to="academic_structure.class",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_extra_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_requests",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_requests",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de séances supplémentaires",
                "verbose_name_plural": "Demandes de séances supplémentaires",
                "db_table": "extra_session_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubjectProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_done",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "extra_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Heures supplémentaires approuvées",
                    ),
                ),
                ("notified_60", models.BooleanField(default=False)),
                ("notified_90", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_progress",
                        to="academic_structure.academicyear",
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_progress",
                        to="academic_structure.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_progress",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression matière",
                "verbose_name_plural": "Progressions matières",
                "db_table": "subject_progress",
                "unique_together": {("subject", "class_group", "academic_year")},
            },
        ),
    ]
