# Generated by Django 5.1.4 on 2026-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_add_qr_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesheet",
            name="absent_auto_done",
            field=models.BooleanField(
                default=False,
                help_text="Vrai une fois que la tâche périodique a marqué les absents de fin de séance.",
                verbose_name="Absences auto-marquées",
            ),
        ),
    ]
