# Generated by Django 5.1.4 on 2026-07-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_add_absent_auto_done"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectprogress",
            options={
                "verbose_name": "Progression module (EC)",
                "verbose_name_plural": "Progressions modules (EC)",
            },
        ),
    ]
