# Generated by Django 5.1.4 on 2026-07-30 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0030_remove_institutpaymentconfig_is_active_and_more"),
        ("attendance", "0007_alter_subjectprogress_options"),
        ("students", "0018_student_country_of_birth_student_nationality"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceAlertConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seuil_absences",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Nombre de séances d'absence non justifiées au-delà duquel une alerte automatique est envoyée au tuteur et au département.",
                        verbose_name="Seuil d'absences",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_alert_config",
                        to="academic_structure.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seuil d'alerte absences",
                "verbose_name_plural": "Seuils d'alerte absences",
                "db_table": "absence_alert_configs",
            },
        ),
        migrations.CreateModel(
            name="StudentAbsenceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("absence_count", models.PositiveIntegerField()),
                ("threshold_used", models.PositiveSmallIntegerField()),
                ("guardian_email_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absence_alerts",
                        to="academic_structure.department",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_alerts",
                        to="academic_structure.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absence_alerts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte absence étudiant",
                "verbose_name_plural": "Alertes absences étudiants",
                "db_table": "student_absence_alerts",
                "unique_together": {("student", "semester")},
            },
        ),
    ]
