# Generated by Django 5.1.4 on 2026-07-30 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0030_remove_institutpaymentconfig_is_active_and_more"),
        ("attendance", "0008_absencealertconfig_studentabsencealert"),
        ("subjects", "0007_alter_subject_options"),
        ("teachers", "0002_teacher_adresse_teacher_date_naissance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "syllabus_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Générés automatiquement et aléatoirement à partir du contenu prévu des séances.",
                        verbose_name="Mots-clés du syllabus",
                    ),
                ),
                (
                    "compliance_checked",
                    models.BooleanField(
                        default=False,
                        help_text="Vrai une fois la vérification de conformité effectuée (sur les 5 premières séances émargées).",
                    ),
                ),
                ("compliance_match_pct", models.FloatField(blank=True, null=True)),
                ("compliance_alert_sent", models.BooleanField(default=False)),
                ("compliance_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_plans",
                        to="academic_structure.academicyear",
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_plans",
                        to="academic_structure.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_plans",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_plans",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de cours",
                "verbose_name_plural": "Plans de cours",
                "db_table": "course_plans",
                "unique_together": {
                    ("subject", "class_group", "academic_year", "teacher")
                },
            },
        ),
        migrations.CreateModel(
            name="CoursePlanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(verbose_name="N° de séance"),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("contenu_prevu", models.TextField(verbose_name="Contenu prévu")),
                (
                    "duree_heures",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Durée prévue (heures)",
                    ),
                ),
                (
                    "course_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="attendance.courseplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance planifiée",
                "verbose_name_plural": "Séances planifiées",
                "db_table": "course_plan_sessions",
                "ordering": ["numero"],
                "unique_together": {("course_plan", "numero")},
            },
        ),
    ]
