# Generated by Django 5.1.4 on 2026-07-30 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_courseplan_courseplansession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="justification_admin_note",
            field=models.TextField(
                blank=True,
                verbose_name="Note de l'administrateur (motif de rejet le cas échéant)",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="justification_reason",
            field=models.TextField(
                blank=True, verbose_name="Motif fourni par l'étudiant"
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="justification_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="justification_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="justification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "En attente"),
                    ("APPROVED", "Approuvée"),
                    ("REJECTED", "Rejetée"),
                ],
                help_text="Vide tant que l'étudiant n'a soumis aucune justification.",
                max_length=10,
                verbose_name="Statut de la justification",
            ),
        ),
        migrations.AddField(
            model_name="studentattendance",
            name="justification_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="justified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date à laquelle la justification a été approuvée (statut passé à Justifiée).",
                null=True,
            ),
        ),
    ]
