# Generated by Django 5.1.4 on 2026-07-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_studentattendance_justification_admin_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseplansession",
            name="objectif",
            field=models.TextField(
                blank=True,
                help_text="Repris automatiquement dans le champ « Objectifs » du cahier de texte à l'émargement.",
                verbose_name="Objectif de la séance",
            ),
        ),
    ]
