# Generated by Django 5.1.4 on 2026-07-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="niveau_entree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L1", "1ère année"),
                    ("L2", "2ième année"),
                    ("L3", "3ième année"),
                    ("L4", "4ième année"),
                    ("L5", "5ième année"),
                ],
                help_text="Déclarée par le candidat — détermine les pièces justificatives demandées (voir required_document_types).",
                max_length=2,
                verbose_name="Année d'entrée",
            ),
        ),
        migrations.CreateModel(
            name="CandidatureDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            (
                                "CNI_PASSEPORT",
                                "Carte Nationale d'Identité ou Passeport",
                            ),
                            ("DIPLOME_BAC", "Diplôme / Attestation du BAC"),
                            ("RELEVE_BAC", "Relevé du BAC"),
                            ("PHOTO_IDENTITE", "Photo d'identité"),
                            ("BULLETIN", "Bulletin de semestre antérieur"),
                        ],
                        max_length=20,
                        verbose_name="Type de pièce",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True,
                        help_text="Ex : « Bulletin semestre 1 » — pour les pièces répétables.",
                        max_length=100,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="admissions/documents_candidature/%Y/%m/",
                        verbose_name="Fichier",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="admissions.candidature",
                        verbose_name="Candidature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce justificative de candidature",
                "verbose_name_plural": "Pièces justificatives de candidature",
                "db_table": "candidature_documents",
                "ordering": ["document_type", "uploaded_at"],
            },
        ),
    ]
