# Generated by Django 5.1.4 on 2026-07-18 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CadrageStrategique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "annee_debut",
                    models.PositiveIntegerField(verbose_name="Année de début"),
                ),
                ("annee_fin", models.PositiveIntegerField(verbose_name="Année de fin")),
                ("vision", models.TextField(verbose_name="Vision")),
                ("mission", models.TextField(verbose_name="Mission")),
                (
                    "valeurs",
                    models.TextField(
                        blank=True,
                        help_text="Une valeur par ligne.",
                        verbose_name="Valeurs",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cadrage stratégique",
                "verbose_name_plural": "Cadrages stratégiques",
                "db_table": "psd_cadrages",
                "ordering": ["-annee_debut"],
            },
        ),
        migrations.CreateModel(
            name="AxeStrategique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "annee_debut",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Année de début"
                    ),
                ),
                (
                    "annee_fin",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Année de fin"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cadrage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="axes",
                        to="strategic_plan.cadragestrategique",
                        verbose_name="Cadrage stratégique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Axe stratégique",
                "verbose_name_plural": "Axes stratégiques",
                "db_table": "psd_axes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ObjectifStrategique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "perspective_bsc",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("financiere", "Financière"),
                            ("clients_etudiants", "Clients / Étudiants"),
                            ("processus_internes", "Processus internes"),
                            ("apprentissage_innovation", "Apprentissage & Innovation"),
                        ],
                        help_text="Renseigner pour faire apparaître cet objectif dans le Balanced Scorecard.",
                        max_length=30,
                        verbose_name="Perspective BSC",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="objectifs",
                        to="strategic_plan.axestrategique",
                        verbose_name="Axe stratégique",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objectifs_strategiques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif stratégique",
                "verbose_name_plural": "Objectifs stratégiques",
                "db_table": "psd_objectifs",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "objectif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programmes",
                        to="strategic_plan.objectifstrategique",
                        verbose_name="Objectif stratégique",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programmes_strategiques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "db_table": "psd_programmes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "budget_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Champ déclaratif — indépendant du suivi réel via les lignes budgétaires.",
                        max_digits=16,
                        verbose_name="Budget total prévisionnel (FCFA)",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("suspendu", "Suspendu"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "taux_avancement",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Recalculé automatiquement à partir des activités.",
                        verbose_name="Taux d'avancement (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projets",
                        to="strategic_plan.programme",
                        verbose_name="Programme",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets_strategiques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "db_table": "psd_projets",
                "ordering": ["-date_debut", "code"],
            },
        ),
        migrations.CreateModel(
            name="Livrable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "date_prevue",
                    models.DateField(blank=True, null=True, verbose_name="Date prévue"),
                ),
                (
                    "date_livraison",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_preparation", "En préparation"),
                            ("livre", "Livré"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_preparation",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="psd/livrables/%Y/%m/",
                        verbose_name="Fichier",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livrables_strategiques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livrables",
                        to="strategic_plan.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livrable",
                "verbose_name_plural": "Livrables",
                "db_table": "psd_livrables",
                "ordering": ["date_prevue"],
            },
        ),
        migrations.CreateModel(
            name="Jalon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                ("date_prevue", models.DateField(verbose_name="Date prévue")),
                (
                    "date_reelle",
                    models.DateField(blank=True, null=True, verbose_name="Date réelle"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("atteint", "Atteint"),
                            ("manque", "Manqué"),
                        ],
                        default="a_venir",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jalons_strategiques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jalons",
                        to="strategic_plan.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jalon",
                "verbose_name_plural": "Jalons",
                "db_table": "psd_jalons",
                "ordering": ["date_prevue"],
            },
        ),
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Budget (FCFA)",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("retardee", "Retardée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "taux_avancement",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Recalculé automatiquement à partir des sous-activités.",
                        verbose_name="Taux d'avancement (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites_strategiques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activites",
                        to="strategic_plan.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
                "db_table": "psd_activites",
                "ordering": ["date_debut", "code"],
            },
        ),
        migrations.CreateModel(
            name="SousActivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="Code"),
                ),
                ("libelle", models.CharField(max_length=250, verbose_name="Libellé")),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("retardee", "Retardée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "taux_avancement",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Taux d'avancement (%)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_activites",
                        to="strategic_plan.activite",
                        verbose_name="Activité",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sous_activites_strategiques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-activité",
                "verbose_name_plural": "Sous-activités",
                "db_table": "psd_sous_activites",
                "ordering": ["date_debut", "code"],
            },
        ),
        migrations.CreateModel(
            name="MembreEquipeProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_dans_projet",
                    models.CharField(
                        max_length=100, verbose_name="Rôle dans le projet"
                    ),
                ),
                (
                    "date_affectation",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date d'affectation"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipes_projets_strategiques",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres_equipe",
                        to="strategic_plan.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre d'équipe projet",
                "verbose_name_plural": "Membres d'équipe projet",
                "db_table": "psd_membres_equipe",
                "unique_together": {("projet", "utilisateur")},
            },
        ),
    ]
