# Generated by Django 5.1.4 on 2026-07-23 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0029_department_admissions_date_fermeture_and_more"),
        ("accounts", "0040_alter_role_name"),
        ("strategic_plan", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanTravailAnnuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans_travail_annuels",
                        to="academic_structure.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans_travail_annuels",
                        to="accounts.direction",
                        verbose_name="Direction",
                    ),
                ),
                (
                    "titulaire",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans_travail_annuels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Titulaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Travail Annuel",
                "verbose_name_plural": "Plans de Travail Annuels",
                "db_table": "psd_pta",
                "ordering": ["-academic_year__start_date", "titulaire__last_name"],
                "unique_together": {("academic_year", "titulaire")},
            },
        ),
        migrations.CreateModel(
            name="PlanTravailAnnuelLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objectif_specifique",
                    models.CharField(
                        max_length=500, verbose_name="Objectif spécifique"
                    ),
                ),
                ("activites", models.TextField(blank=True, verbose_name="Activités")),
                (
                    "delai_realisation",
                    models.CharField(
                        blank=True,
                        help_text='Date, mois ou période libre — ex. "Toute l\'année", "Octobre-Décembre 2026".',
                        max_length=200,
                        verbose_name="Délai de réalisation",
                    ),
                ),
                (
                    "indicateur_performance",
                    models.TextField(
                        blank=True, verbose_name="Indicateur de performance"
                    ),
                ),
                (
                    "element_preuve",
                    models.TextField(blank=True, verbose_name="Élément de preuve"),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "objectif_strategique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_pta",
                        to="strategic_plan.objectifstrategique",
                        verbose_name="Objectif stratégique",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="strategic_plan.plantravailannuel",
                        verbose_name="PTA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de PTA",
                "verbose_name_plural": "Lignes de PTA",
                "db_table": "psd_pta_lignes",
                "ordering": [
                    "objectif_strategique__axe__code",
                    "objectif_strategique__code",
                    "ordre",
                    "pk",
                ],
            },
        ),
    ]
