# Generated by Django 5.1.4 on 2026-07-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategic_plan", "0002_plantravailannuel_plantravailannuelligne"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantravailannuelligne",
            name="realisations",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "0%"),
                    (10, "10%"),
                    (20, "20%"),
                    (30, "30%"),
                    (40, "40%"),
                    (50, "50%"),
                    (60, "60%"),
                    (70, "70%"),
                    (80, "80%"),
                    (90, "90%"),
                    (100, "100%"),
                ],
                default=0,
                help_text="Niveau de réalisation de l'activité, par palier de 10%.",
                verbose_name="Réalisations (%)",
            ),
        ),
    ]
