# Generated by Django 5.1.4 on 2026-07-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategic_plan", "0003_plantravailannuelligne_realisations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantravailannuelligne",
            name="delai_realisation",
        ),
        migrations.AddField(
            model_name="plantravailannuelligne",
            name="date_debut_activite",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de début d'activité"
            ),
        ),
        migrations.AddField(
            model_name="plantravailannuelligne",
            name="date_fin_activite",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin d'activité"
            ),
        ),
    ]
