# Generated by Django 5.1.4 on 2026-07-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "strategic_plan",
            "0004_remove_plantravailannuelligne_delai_realisation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantravailannuelligne",
            name="objectif_specifique",
        ),
        migrations.AlterField(
            model_name="plantravailannuelligne",
            name="objectif_strategique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_pta",
                to="strategic_plan.objectifstrategique",
                verbose_name="Objectifs stratégiques",
            ),
        ),
    ]
