# Generated by Django 5.1.4 on 2026-07-09 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_conversation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation RYTAL",
                "verbose_name_plural": "Conversations RYTAL",
                "db_table": "chatbot_conversations",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Utilisateur"), ("assistant", "RYTAL")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_welcome",
                    models.BooleanField(
                        default=False,
                        help_text="Message de bienvenue généré automatiquement, exclu du contexte envoyé au LLM.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message RYTAL",
                "verbose_name_plural": "Messages RYTAL",
                "db_table": "chatbot_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="chatbot_mes_convers_9b53f8_idx",
                    )
                ],
            },
        ),
    ]
