# Generated by Django 5.1.4 on 2026-06-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_GRADE", "Nouvelle note"),
                    ("ABSENCE", "Absence enregistrée"),
                    ("COURSE_CANCELLED", "Cours annulé/reporté"),
                    ("TIMETABLE_CHANGE", "Modification emploi du temps"),
                    ("SHEET_VALIDATED", "Émargement validé"),
                    ("EVAL_DEVOIR", "Programmer un devoir"),
                    ("EVAL_EXAMEN", "Programmer un examen"),
                    ("VOL_COMPLETE", "Volume horaire atteint"),
                    ("EXTRA_REQUEST", "Demande séances supplémentaires"),
                    ("EXTRA_APPROVED", "Demande approuvée"),
                    ("EXTRA_REJECTED", "Demande rejetée"),
                    ("GENERAL", "Notification générale"),
                    ("COURSE_SUPPORT", "Support de cours partagé"),
                ],
                max_length=25,
            ),
        ),
    ]
