# Generated by Django 5.1.4 on 2026-07-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_add_inscription_notification_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_GRADE", "Nouvelle note"),
                    ("ABSENCE", "Absence enregistrée"),
                    ("COURSE_CANCELLED", "Cours annulé/reporté"),
                    ("TIMETABLE_CHANGE", "Modification emploi du temps"),
                    ("SHEET_VALIDATED", "Émargement validé"),
                    ("EVAL_DEVOIR", "Programmer un devoir"),
                    ("EVAL_EXAMEN", "Programmer un examen"),
                    ("VOL_COMPLETE", "Volume horaire atteint"),
                    ("EXTRA_REQUEST", "Demande séances supplémentaires"),
                    ("EXTRA_APPROVED", "Demande approuvée"),
                    ("EXTRA_REJECTED", "Demande rejetée"),
                    ("GENERAL", "Notification générale"),
                    ("COURSE_SUPPORT", "Support de cours partagé"),
                    ("INSCRIPTION_PENDING", "Demande d'inscription en attente"),
                    ("INSCRIPTION_VALIDATED", "Inscription validée"),
                    ("INSCRIPTION_REJECTED", "Inscription rejetée"),
                    ("HR_LEAVE", "Congé — décision"),
                    ("HR_DISCIPLINE", "Dossier disciplinaire"),
                    ("HR_EVALUATION", "Évaluation"),
                    ("HR_MISSION", "Mission"),
                    ("HR_INTERIM", "Intérim"),
                    ("HR_HANDOVER", "Passation de service"),
                    ("HR_INTERNSHIP", "Stage"),
                    ("HR_ONBOARDING", "Intégration"),
                    ("HR_RECRUITMENT", "Recrutement"),
                    ("HR_DOCUMENT", "Document RH"),
                ],
                max_length=25,
            ),
        ),
    ]
