# Generated by Django 5.1.4 on 2026-07-01 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletinSalaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField(verbose_name="Année")),
                ("mois", models.PositiveSmallIntegerField(verbose_name="Mois")),
                (
                    "salaire_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Salaire de base (FCFA)",
                    ),
                ),
                (
                    "primes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Primes / Indemnités (FCFA)",
                    ),
                ),
                (
                    "retenues",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Retenues / Cotisations (FCFA)",
                    ),
                ),
                (
                    "salaire_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Net à payer (FCFA)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("PAYE", "Payé"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bulletin de salaire",
                "verbose_name_plural": "Bulletins de salaire",
                "db_table": "hr_bulletin_salaire",
                "ordering": ["-annee", "-mois", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="FichePersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Poste / Fonction"
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("STAGE", "Stage"),
                            ("PRESTATAIRE", "Prestataire"),
                            ("VACATION", "Vacation"),
                        ],
                        default="CDI",
                        max_length=15,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "date_embauche",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
                (
                    "date_fin_contrat",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin de contrat"
                    ),
                ),
                (
                    "numero_cnss",
                    models.CharField(blank=True, max_length=30, verbose_name="N° CNSS"),
                ),
                (
                    "numero_ipres",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="N° IPRES"
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "contact_urgence_nom",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Contact d'urgence — Nom",
                    ),
                ),
                (
                    "contact_urgence_telephone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Contact d'urgence — Téléphone",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes RH")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fiche personnel",
                "verbose_name_plural": "Fiches personnel",
                "db_table": "hr_fiche_personnel",
            },
        ),
        migrations.CreateModel(
            name="SalaireConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salaire_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Salaire de base (FCFA)",
                    ),
                ),
                (
                    "primes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Primes / Indemnités (FCFA)",
                    ),
                ),
                (
                    "retenues",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Retenues / Cotisations (FCFA)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Détail des primes et retenues"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration salariale",
                "verbose_name_plural": "Configurations salariales",
                "db_table": "hr_salaire_config",
            },
        ),
        migrations.RenameIndex(
            model_name="demandeconge",
            new_name="demandes_co_user_id_377375_idx",
            old_name="conge_user_statut_idx",
        ),
        migrations.RenameIndex(
            model_name="demandeconge",
            new_name="demandes_co_date_de_9082d4_idx",
            old_name="conge_dates_idx",
        ),
        migrations.RenameIndex(
            model_name="staffpresence",
            new_name="staff_prese_date_46af14_idx",
            old_name="staff_pres_date_idx",
        ),
        migrations.RenameIndex(
            model_name="staffpresence",
            new_name="staff_prese_user_id_e265fb_idx",
            old_name="staff_pres_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="staffpresence",
            new_name="staff_prese_statut_261822_idx",
            old_name="staff_pres_statut_idx",
        ),
        migrations.AddField(
            model_name="bulletinsalaire",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletins_salaire_generes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Généré par",
            ),
        ),
        migrations.AddField(
            model_name="bulletinsalaire",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulletins_salaire",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employé",
            ),
        ),
        migrations.AddField(
            model_name="bulletinsalaire",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletins_salaire_valides",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validé par",
            ),
        ),
        migrations.AddField(
            model_name="fichepersonnel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fiche_personnel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employé",
            ),
        ),
        migrations.AddField(
            model_name="salaireconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salaire_configs_modifies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifié par",
            ),
        ),
        migrations.AddField(
            model_name="salaireconfig",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salaire_config",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Employé",
            ),
        ),
        migrations.AddIndex(
            model_name="bulletinsalaire",
            index=models.Index(
                fields=["annee", "mois"], name="hr_bulletin_annee_2961d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulletinsalaire",
            index=models.Index(
                fields=["user", "annee", "mois"], name="hr_bulletin_user_id_a9a33e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bulletinsalaire",
            unique_together={("user", "annee", "mois")},
        ),
    ]
