# Generated by Django 5.1.4 on 2026-07-15 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0020_fix_faculty_institutconfig_cross_db_fk"),
        ("hr", "0002_bulletinsalaire_fichepersonnel_salaireconfig_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField(verbose_name="Année")),
                ("label", models.CharField(max_length=150, verbose_name="Libellé")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("OUVERTE", "Ouverte"),
                            ("CLOTUREE", "Clôturée"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Campagne d'évaluation",
                "verbose_name_plural": "Campagnes d'évaluation",
                "db_table": "hr_evaluation_campaign",
                "ordering": ["-annee"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poste",
                    models.CharField(blank=True, max_length=150, verbose_name="Poste"),
                ),
                ("date_effet", models.DateField(verbose_name="Date d'effet")),
                (
                    "type_affectation",
                    models.CharField(
                        choices=[
                            ("RECRUTEMENT", "Recrutement"),
                            ("PROMOTION", "Promotion"),
                            ("MOBILITE", "Mobilité interne"),
                        ],
                        default="MOBILITE",
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affectations_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="academic_structure.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affectations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation",
                "verbose_name_plural": "Affectations (carrière)",
                "db_table": "hr_assignment",
                "ordering": ["-date_effet"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "CDI"),
                            ("CDD", "CDD"),
                            ("STAGE", "Stage"),
                            ("INTERIM", "Intérim"),
                            ("PRESTATION", "Prestation"),
                        ],
                        default="CDI",
                        max_length=15,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "salaire_brut",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salaire brut (FCFA)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("SUSPENDU", "Suspendu"),
                            ("TERMINE", "Terminé"),
                        ],
                        default="ACTIF",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "signe_le",
                    models.DateField(blank=True, null=True, verbose_name="Signé le"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contrats_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "db_table": "hr_contract",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="ContractAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_effet", models.DateField(verbose_name="Date d'effet")),
                ("objet", models.CharField(max_length=200, verbose_name="Objet")),
                ("details", models.TextField(blank=True, verbose_name="Détails")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avenants",
                        to="hr.contract",
                        verbose_name="Contrat",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avenants_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avenant",
                "verbose_name_plural": "Avenants",
                "db_table": "hr_contract_amendment",
                "ordering": ["-date_effet"],
            },
        ),
        migrations.CreateModel(
            name="DisciplinaryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motif", models.TextField(verbose_name="Motif")),
                (
                    "explication",
                    models.TextField(
                        blank=True, verbose_name="Explication de l'employé"
                    ),
                ),
                (
                    "sanction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AVERTISSEMENT", "Avertissement"),
                            ("BLAME", "Blâme"),
                            ("MISE_A_PIED", "Mise à pied"),
                            ("LICENCIEMENT", "Licenciement"),
                        ],
                        max_length=15,
                        verbose_name="Type de sanction",
                    ),
                ),
                ("decision", models.TextField(blank=True, verbose_name="Décision")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DEMANDE_EXPLICATION", "Demande d'explication"),
                            ("REPONSE_RECUE", "Réponse reçue"),
                            ("CONSEIL", "Conseil de discipline"),
                            ("SANCTION", "Sanction prononcée"),
                            ("CLASSE", "Classé sans suite"),
                        ],
                        default="DEMANDE_EXPLICATION",
                        max_length=25,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_disciplinaires_inities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initié par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dossiers_disciplinaires",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier disciplinaire",
                "verbose_name_plural": "Dossiers disciplinaires",
                "db_table": "hr_disciplinary_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(max_length=60, verbose_name="Catégorie"),
                ),
                (
                    "fichier",
                    models.FileField(upload_to="hr/documents/", verbose_name="Fichier"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents_rh_uploades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Déposé par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_rh",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "hr_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("ATTESTATION_TRAVAIL", "Attestation de travail"),
                            ("ATTESTATION_SALAIRE", "Attestation de salaire"),
                            ("CERTIFICAT_TRAVAIL", "Certificat de travail"),
                        ],
                        max_length=25,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SOUMISE", "Soumise"),
                            ("EN_TRAITEMENT", "En traitement"),
                            ("SIGNEE", "Signée"),
                            ("DISPONIBLE", "Disponible"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="SOUMISE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_documents_traitees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes",
                        to="hr.document",
                        verbose_name="Document généré",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de document",
                "verbose_name_plural": "Demandes de documents",
                "db_table": "hr_document_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "À faire"),
                            ("AUTO_EVALUEE", "Auto-évaluée"),
                            ("EVALUEE", "Évaluée"),
                            ("FINALISEE", "Finalisée"),
                        ],
                        default="A_FAIRE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "auto_evaluation",
                    models.TextField(blank=True, verbose_name="Auto-évaluation"),
                ),
                (
                    "souhait_carriere",
                    models.TextField(blank=True, verbose_name="Souhaits de carrière"),
                ),
                (
                    "evaluation_manager",
                    models.TextField(
                        blank=True, verbose_name="Évaluation du responsable"
                    ),
                ),
                (
                    "note_globale",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Note globale (1 à 5)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_realisees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Évalué par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="hr.evaluationcampaign",
                        verbose_name="Campagne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "db_table": "hr_evaluation",
                "ordering": ["-campaign__annee", "user__last_name"],
                "unique_together": {("campaign", "user")},
            },
        ),
        migrations.CreateModel(
            name="EvaluationObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "poids",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Poids"),
                ),
                ("resultat", models.TextField(blank=True, verbose_name="Résultat")),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs",
                        to="hr.evaluation",
                        verbose_name="Évaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif d'évaluation",
                "verbose_name_plural": "Objectifs d'évaluation",
                "db_table": "hr_evaluation_objective",
            },
        ),
        migrations.CreateModel(
            name="Handover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poste",
                    models.CharField(max_length=255, verbose_name="Poste concerné"),
                ),
                ("date_passation", models.DateField(verbose_name="Date de passation")),
                (
                    "elements_transferes",
                    models.TextField(blank=True, verbose_name="Éléments transférés"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("SOUMISE", "Soumise"), ("VALIDEE", "Validée")],
                        default="SOUMISE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passations_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "entrant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passations_entrant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent entrant",
                    ),
                ),
                (
                    "sortant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passations_sortant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent sortant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passation de service",
                "verbose_name_plural": "Passations de service",
                "db_table": "hr_handover",
                "ordering": ["-date_passation"],
            },
        ),
        migrations.CreateModel(
            name="Interim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("CONGE", "Congé"),
                            ("ABSENCE", "Absence"),
                            ("MISSION", "Mission"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                        verbose_name="Motif",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOTUREE", "Clôturée")],
                        default="ACTIVE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interims_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "interimaire",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interims_remplacant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Intérimaire",
                    ),
                ),
                (
                    "titulaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interims_titulaire",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Titulaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intérim",
                "verbose_name_plural": "Intérims",
                "db_table": "hr_interim",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "ecole",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="École / Établissement"
                    ),
                ),
                (
                    "sujet",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sujet de stage"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DEMANDE", "Demande"),
                            ("ENTRETIEN", "Entretien"),
                            ("ACCEPTE", "Accepté"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="DEMANDE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stages_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "tuteur",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stagiaires_encadres",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tuteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
                "db_table": "hr_internship",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objet", models.CharField(max_length=255, verbose_name="Objet")),
                (
                    "destination",
                    models.CharField(max_length=120, verbose_name="Destination"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                ("date_fin", models.DateField(verbose_name="Date de fin")),
                (
                    "rapport",
                    models.TextField(blank=True, verbose_name="Rapport de mission"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SOUMISE", "Soumise"),
                            ("VALIDEE", "Validée"),
                            ("EFFECTUEE", "Effectuée"),
                            ("RAPPORT_REMIS", "Rapport remis"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="SOUMISE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions_validees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "db_table": "hr_mission",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "statut",
                    models.CharField(
                        choices=[("EN_COURS", "En cours"), ("TERMINE", "Terminé")],
                        default="EN_COURS",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboardings_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboardings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intégration",
                "verbose_name_plural": "Intégrations",
                "db_table": "hr_onboarding",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Tâche")),
                (
                    "responsable",
                    models.CharField(
                        default="RH", max_length=50, verbose_name="Responsable"
                    ),
                ),
                ("fait", models.BooleanField(default=False, verbose_name="Fait")),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "onboarding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches",
                        to="hr.onboarding",
                        verbose_name="Intégration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche d'intégration",
                "verbose_name_plural": "Tâches d'intégration",
                "db_table": "hr_onboarding_task",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre du poste"),
                ),
                (
                    "poste",
                    models.CharField(blank=True, max_length=150, verbose_name="Poste"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("INTERNE", "Recrutement interne"),
                            ("EXTERNE", "Appel externe"),
                        ],
                        default="EXTERNE",
                        max_length=10,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description du besoin"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("SOUMISE", "Soumise"),
                            ("VALIDEE", "Validée"),
                            ("EN_COURS", "En cours"),
                            ("POURVUE", "Pourvue"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="SOUMISE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demande_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="besoins_recrutement",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandé par",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="academic_structure.department",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Besoin de recrutement",
                "verbose_name_plural": "Besoins de recrutement",
                "db_table": "hr_recruitment_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="Source"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("CANDIDATURE", "Candidature reçue"),
                            ("PRESELECTIONNE", "Présélectionné"),
                            ("ENTRETIEN", "Entretien"),
                            ("RETENU", "Retenu"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="CANDIDATURE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Score"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruitment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidats",
                        to="hr.recruitmentrequest",
                        verbose_name="Besoin de recrutement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidat",
                "verbose_name_plural": "Candidats",
                "db_table": "hr_candidate",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HRWorkflowEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=30, verbose_name="Module")),
                (
                    "object_id",
                    models.PositiveIntegerField(verbose_name="Identifiant objet"),
                ),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                (
                    "from_statut",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Statut initial"
                    ),
                ),
                (
                    "to_statut",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Statut final"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_workflow_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de workflow RH",
                "verbose_name_plural": "Événements de workflow RH",
                "db_table": "hr_workflow_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["module", "object_id"],
                        name="hr_workflow_module_86c54c_idx",
                    )
                ],
            },
        ),
    ]
