# Generated by Django 5.1.4 on 2026-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_evaluationcampaign_assignment_contract_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccueilScanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[("student", "Étudiant"), ("staff", "Personnel")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Résultat du scan")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
            ],
            options={
                "verbose_name": "Évènement de scan accueil",
                "verbose_name_plural": "Évènements de scan accueil",
                "db_table": "hr_accueil_scan_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="hr_accueil__created_66321c_idx"
                    )
                ],
            },
        ),
    ]
