# Generated by Django 5.1.4 on 2026-06-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Bâtiment",
                "verbose_name_plural": "Bâtiments",
                "db_table": "buildings",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("AMPHI", "Amphithéâtre"),
                            ("SALLE", "Salle de cours"),
                            ("LABO", "Laboratoire"),
                            ("TD", "Salle de TD"),
                        ],
                        default="SALLE",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(verbose_name="Capacité")),
                (
                    "has_projector",
                    models.BooleanField(default=False, verbose_name="Projecteur"),
                ),
                (
                    "has_ac",
                    models.BooleanField(default=False, verbose_name="Climatisation"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="rooms.building",
                        verbose_name="Bâtiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salle",
                "verbose_name_plural": "Salles",
                "db_table": "rooms",
                "ordering": ["building", "code"],
            },
        ),
    ]
