# Generated by Django 5.1.4 on 2026-06-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_structure", "0001_initial"),
        ("rooms", "0001_initial"),
        ("subjects", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Lundi"),
                            (2, "Mardi"),
                            (3, "Mercredi"),
                            (4, "Jeudi"),
                            (5, "Vendredi"),
                            (6, "Samedi"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Hebdomadaire"),
                            ("BIWEEKLY", "Bi-hebdomadaire"),
                            ("ONCE", "Ponctuel"),
                        ],
                        default="WEEKLY",
                        max_length=15,
                    ),
                ),
                (
                    "specific_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date spécifique (si ponctuel)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3788d8", max_length=7, verbose_name="Couleur"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academic_structure.class",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="rooms.room",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="academic_structure.semester",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée emploi du temps",
                "verbose_name_plural": "Emplois du temps",
                "db_table": "timetable_entries",
            },
        ),
        migrations.CreateModel(
            name="TimetableConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("TEACHER", "Conflit enseignant"),
                            ("ROOM", "Conflit salle"),
                            ("CLASS", "Conflit classe"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "entry_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_first",
                        to="timetable.timetableentry",
                    ),
                ),
                (
                    "entry_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_as_second",
                        to="timetable.timetableentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conflit emploi du temps",
                "db_table": "timetable_conflicts",
            },
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["semester", "class_group"],
                name="timetable_e_semeste_d1bceb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["teacher", "day_of_week"], name="timetable_e_teacher_7daf0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableentry",
            index=models.Index(
                fields=["room", "day_of_week"], name="timetable_e_room_id_392fe8_idx"
            ),
        ),
    ]
