# Generated by Django 5.1.4 on 2026-06-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField(verbose_name="Date de la séance")),
                ("objectives", models.TextField(verbose_name="Objectifs de la séance")),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Contenu réalisé"),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="Observations")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_logs",
                        to="timetable.timetableentry",
                        verbose_name="Créneau",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de séance",
                "db_table": "timetable_session_logs",
                "ordering": ["session_date"],
                "unique_together": {("timetable_entry", "session_date")},
            },
        ),
    ]
