# Generated by Django 5.1.4 on 2026-06-24 18:02

import academic_core.apps.timetable.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0014_semester_session_cloture"),
        ("subjects", "0005_course_support"),
        ("teachers", "0001_initial"),
        ("timetable", "0002_session_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du support"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("CM", "Cours Magistral (CM)"),
                            ("TD", "Travaux Dirigés (TD)"),
                            ("TP", "Travaux Pratiques (TP)"),
                            ("AUTRE", "Autre"),
                        ],
                        default="CM",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=academic_core.apps.timetable.models._support_upload_path,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Partagé le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_supports",
                        to="academic_structure.class",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_supports",
                        to="academic_structure.semester",
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_supports",
                        to="subjects.subject",
                        verbose_name="Matière",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_supports",
                        to="teachers.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support de cours",
                "verbose_name_plural": "Supports de cours",
                "db_table": "course_supports",
                "ordering": ["-shared_at"],
            },
        ),
    ]
