# Generated by Django 5.1.4 on 2026-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_planning_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableentry",
            name="day_of_week",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Lundi"),
                    (2, "Mardi"),
                    (3, "Mercredi"),
                    (4, "Jeudi"),
                    (5, "Vendredi"),
                    (6, "Samedi"),
                    (7, "Dimanche"),
                ]
            ),
        ),
    ]
