# Generated by Django 5.1.4 on 2026-07-11 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0007_alter_subject_options"),
        ("timetable", "0006_sessionlog_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesupport",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_supports",
                to="subjects.subject",
                verbose_name="Module (EC)",
            ),
        ),
    ]
