# Generated by Django 5.1.4 on 2026-06-16 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "db_table": "teacher_grades",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricule",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Matricule"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(max_length=200, verbose_name="Spécialité"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent"),
                            ("VACATAIRE", "Vacataire"),
                        ],
                        default="PERMANENT",
                        max_length=20,
                    ),
                ),
                (
                    "contractual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Volume horaire contractuel",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="teachers.grade",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enseignant",
                "verbose_name_plural": "Enseignants",
                "db_table": "teachers",
            },
        ),
    ]
