# Generated by Django 5.1.4 on 2026-07-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0017_semester_is_locked_semester_locked_at_and_more"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="adresse",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Adresse complète"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="date_naissance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="lieu_naissance",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="lieu_residence",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Lieu de résidence habituelle"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="nationalite",
            field=models.CharField(
                blank=True,
                default="Sénégalaise",
                max_length=100,
                verbose_name="Nationalité",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="ninea",
            field=models.CharField(blank=True, max_length=50, verbose_name="NINEA"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="num_cin_passeport",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="N° CIN / Passeport"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="profession",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="situation_matrimoniale",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CELIBATAIRE", "Célibataire"),
                    ("MARIE", "Marié(e)"),
                    ("DIVORCE", "Divorcé(e)"),
                    ("VEUF", "Veuf(ve)"),
                ],
                max_length=20,
                verbose_name="Situation matrimoniale",
            ),
        ),
        migrations.CreateModel(
            name="ContratEnseignant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lieu_signature",
                    models.CharField(
                        blank=True,
                        default="Dakar",
                        max_length=100,
                        verbose_name="Lieu de signature",
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de signature"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats_enseignants",
                        to="academic_structure.academicyear",
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats_enseignants",
                        to="academic_structure.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="teachers.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat enseignant",
                "verbose_name_plural": "Contrats enseignants",
                "db_table": "contrats_enseignants",
                "ordering": ["department__name", "teacher__user__last_name"],
                "unique_together": {("teacher", "department", "academic_year")},
            },
        ),
    ]
