# Generated by Django 5.1.4 on 2026-08-01 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_structure", "0031_diplomasupplementconfig"),
        ("students", "0018_student_country_of_birth_student_nationality"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "type_activite",
                    models.CharField(
                        choices=[
                            ("CONFERENCE", "Conférence"),
                            ("ATELIER", "Atelier"),
                            ("SEMINAIRE", "Séminaire"),
                            ("FORUM", "Forum"),
                            ("JOURNEE_CARRIERE", "Journée carrière"),
                            ("VISITE", "Visite"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                        verbose_name="Type d'activité",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("objectifs", models.TextField(blank=True, verbose_name="Objectifs")),
                (
                    "date_debut",
                    models.DateTimeField(verbose_name="Date/heure de début"),
                ),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date/heure de fin"
                    ),
                ),
                (
                    "lieu",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifiée"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminée"),
                            ("ANNULE", "Annulée"),
                        ],
                        default="PLANIFIE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "programme",
                    models.TextField(blank=True, verbose_name="Programme détaillé"),
                ),
                (
                    "compte_rendu",
                    models.TextField(blank=True, verbose_name="Compte-rendu"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites_coip_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites_coip_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité COIP",
                "verbose_name_plural": "Activités COIP",
                "db_table": "coip_activity",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="ActivityPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="coip/activities/photos/")),
                (
                    "legende",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="coip.activity",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo d'activité",
                "verbose_name_plural": "Photos d'activité",
                "db_table": "coip_activity_photo",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Alumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "promotion",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Promotion"
                    ),
                ),
                (
                    "diplome",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Diplôme obtenu"
                    ),
                ),
                (
                    "annee_obtention",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Année d'obtention"
                    ),
                ),
                (
                    "entreprise_actuelle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Entreprise actuelle"
                    ),
                ),
                (
                    "poste_occupe",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Poste occupé"
                    ),
                ),
                (
                    "secteur_activite",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INFORMATIQUE", "Informatique / Numérique"),
                            ("FINANCE", "Finance / Banque / Assurance"),
                            ("SANTE", "Santé"),
                            ("EDUCATION", "Éducation / Formation"),
                            ("INDUSTRIE", "Industrie"),
                            ("COMMERCE", "Commerce / Distribution"),
                            ("ADMIN_PUBLIQUE", "Administration publique"),
                            ("BTP", "BTP / Construction"),
                            ("TELECOMS", "Télécommunications"),
                            ("ONG", "ONG / Associatif"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Secteur d'activité",
                    ),
                ),
                (
                    "is_employed",
                    models.BooleanField(default=False, verbose_name="En activité"),
                ),
                (
                    "pays",
                    models.CharField(blank=True, max_length=100, verbose_name="Pays"),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, verbose_name="Profil LinkedIn"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="coip/alumni/",
                        verbose_name="Photo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "filiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni",
                        to="academic_structure.program",
                        verbose_name="Filière",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni_profile",
                        to="students.student",
                        verbose_name="Étudiant (dossier académique)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumni",
                "verbose_name_plural": "Alumni",
                "db_table": "coip_alumni",
                "ordering": ["-annee_obtention", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="AlumniCareerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "entreprise",
                    models.CharField(max_length=200, verbose_name="Entreprise"),
                ),
                ("poste", models.CharField(max_length=200, verbose_name="Poste")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_events",
                        to="coip.alumni",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de carrière",
                "verbose_name_plural": "Événements de carrière",
                "db_table": "coip_alumni_career_event",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("CONVENTION", "Convention"),
                            ("RAPPORT", "Rapport"),
                            ("RECOMMANDATION", "Recommandation"),
                            ("ACTIVITE", "Activité"),
                            ("SORTIE", "Sortie pédagogique"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="coip/archives/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Tags (séparés par des virgules)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depose_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives_deposees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Déposé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive",
                "verbose_name_plural": "Archives",
                "db_table": "coip_archive",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="coip/archives/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                ("version", models.CharField(max_length=20, verbose_name="Version")),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="coip.archive",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Version d'archive",
                "verbose_name_plural": "Versions d'archive",
                "db_table": "coip_archive_version",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EducationalVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=200, verbose_name="Intitulé")),
                ("lieu", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "date_depart",
                    models.DateTimeField(verbose_name="Date/heure de départ"),
                ),
                (
                    "date_retour",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date/heure de retour"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "objectifs",
                    models.TextField(blank=True, verbose_name="Objectifs pédagogiques"),
                ),
                (
                    "transport",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Moyen de transport"
                    ),
                ),
                (
                    "nombre_places",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Nombre de places"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifiée"),
                            ("VALIDE", "Validée"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminée"),
                            ("ANNULE", "Annulée"),
                        ],
                        default="PLANIFIE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "rapport",
                    models.TextField(blank=True, verbose_name="Rapport / compte-rendu"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sorties_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sorties_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sortie pédagogique",
                "verbose_name_plural": "Sorties pédagogiques",
                "db_table": "coip_educational_visit",
                "ordering": ["-date_depart"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "type_opportunite",
                    models.CharField(
                        choices=[
                            ("EMPLOI", "Emploi"),
                            ("STAGE", "Stage"),
                            ("BOURSE", "Bourse"),
                            ("FORMATION", "Formation"),
                        ],
                        default="EMPLOI",
                        max_length=15,
                        verbose_name="Type d'opportunité",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "lieu",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "remuneration",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Rémunération"
                    ),
                ),
                (
                    "date_limite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date limite de candidature"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PUBLIE", "Publiée"),
                            ("FERME", "Fermée"),
                            ("EXPIRE", "Expirée"),
                        ],
                        default="PUBLIE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filiere_cible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="academic_structure.program",
                        verbose_name="Filière ciblée",
                    ),
                ),
                (
                    "niveau_cible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to="academic_structure.level",
                        verbose_name="Niveau ciblé",
                    ),
                ),
                (
                    "publie_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunites_publiees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunité",
                "verbose_name_plural": "Opportunités",
                "db_table": "coip_opportunity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lettre_motivation",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="coip/applications/lettres/",
                        verbose_name="Lettre de motivation",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="coip/applications/cv/",
                        verbose_name="CV",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SOUMIS", "Soumise"),
                            ("EN_EXAMEN", "En examen"),
                            ("RETENU", "Candidature retenue"),
                            ("REJETE", "Rejetée"),
                            ("EMBAUCHE", "Embauché(e)"),
                        ],
                        default="SOUMIS",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="students.student",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="coip.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature",
                "verbose_name_plural": "Candidatures",
                "db_table": "coip_job_application",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="OrientationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_session",
                    models.CharField(
                        choices=[
                            ("ENTRETIEN", "Entretien individuel"),
                            ("COACHING", "Coaching"),
                            ("ACCOMPAGNEMENT", "Accompagnement de projet"),
                            ("BILAN", "Bilan de compétences"),
                        ],
                        default="ENTRETIEN",
                        max_length=20,
                        verbose_name="Type de séance",
                    ),
                ),
                (
                    "date_session",
                    models.DateTimeField(verbose_name="Date de la séance"),
                ),
                (
                    "duree_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                (
                    "recommandations",
                    models.TextField(blank=True, verbose_name="Recommandations"),
                ),
                (
                    "objectifs_fixes",
                    models.TextField(blank=True, verbose_name="Objectifs fixés"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conseiller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orientation_sessions_menees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Conseiller",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orientation_sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance d'orientation",
                "verbose_name_plural": "Séances d'orientation",
                "db_table": "coip_orientation_session",
                "ordering": ["-date_session"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                (
                    "type_partenaire",
                    models.CharField(
                        choices=[
                            ("ENTREPRISE", "Entreprise"),
                            ("INSTITUTION", "Institution d'enseignement"),
                            ("ONG", "ONG"),
                            ("ADMIN_PUBLIQUE", "Administration publique"),
                            ("AUTRE", "Autre"),
                        ],
                        default="ENTREPRISE",
                        max_length=20,
                        verbose_name="Type de partenaire",
                    ),
                ),
                (
                    "secteur",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Secteur d'activité"
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "pays",
                    models.CharField(
                        blank=True,
                        default="Sénégal",
                        max_length=100,
                        verbose_name="Pays",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="coip/partners/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partenaires_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "db_table": "coip_partner",
                "ordering": ["raison_sociale"],
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="coip.partner",
                verbose_name="Partenaire",
            ),
        ),
        migrations.CreateModel(
            name="InternshipOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Titre du poste"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description / missions"),
                ),
                (
                    "type_stage",
                    models.CharField(
                        choices=[
                            ("ACADEMIQUE", "Stage académique"),
                            ("PROFESSIONNEL", "Stage professionnel"),
                            ("PFE", "Projet de fin d'études"),
                        ],
                        default="ACADEMIQUE",
                        max_length=15,
                        verbose_name="Type de stage",
                    ),
                ),
                (
                    "duree",
                    models.CharField(blank=True, max_length=100, verbose_name="Durée"),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début souhaitée"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin souhaitée"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert"),
                            ("FERME", "Fermé"),
                            ("POURVU", "Pourvu"),
                        ],
                        default="OUVERT",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "remunere",
                    models.BooleanField(default=False, verbose_name="Rémunéré"),
                ),
                (
                    "montant_remuneration",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Montant de la rémunération",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offres_stage_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "filiere_cible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internship_offers",
                        to="academic_structure.program",
                        verbose_name="Filière ciblée",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internship_offers",
                        to="coip.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre de stage",
                "verbose_name_plural": "Offres de stage",
                "db_table": "coip_internship_offer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=200, verbose_name="Intitulé du stage"),
                ),
                (
                    "encadreur_entreprise",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Encadreur en entreprise",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRME", "Confirmé"),
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Terminé"),
                            ("ABANDONNE", "Abandonné"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "rapport",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="coip/internships/rapports/",
                        verbose_name="Rapport de stage",
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Note",
                    ),
                ),
                (
                    "appreciation",
                    models.TextField(blank=True, verbose_name="Appréciation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encadreur_isi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stages_encadres",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Encadreur académique",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="students.student",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internships",
                        to="coip.internshipoffer",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="coip.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
                "db_table": "coip_internship",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="partenaires",
            field=models.ManyToManyField(
                blank=True,
                related_name="activites_coip",
                to="coip.partner",
                verbose_name="Partenaires associés",
            ),
        ),
        migrations.CreateModel(
            name="PartnerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "poste",
                    models.CharField(blank=True, max_length=150, verbose_name="Poste"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Contact principal"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="coip.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact partenaire",
                "verbose_name_plural": "Contacts partenaire",
                "db_table": "coip_partner_contact",
                "ordering": ["-is_primary", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Partnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intitule",
                    models.CharField(
                        max_length=255, verbose_name="Intitulé de la convention"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date_signature", models.DateField(verbose_name="Date de signature")),
                (
                    "date_expiration",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours de négociation"),
                            ("ACTIVE", "Active"),
                            ("EXPIREE", "Expirée"),
                            ("RESILIEE", "Résiliée"),
                        ],
                        default="EN_COURS",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="coip/conventions/",
                        verbose_name="Document (convention)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships",
                        to="coip.partner",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partenariats_geres",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable COIP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convention de partenariat",
                "verbose_name_plural": "Conventions de partenariat",
                "db_table": "coip_partnership",
                "ordering": ["-date_signature"],
            },
        ),
        migrations.CreateModel(
            name="CollaborationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "type_collaboration",
                    models.CharField(
                        max_length=150, verbose_name="Type de collaboration"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "partnership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_history",
                        to="coip.partnership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de collaboration",
                "verbose_name_plural": "Historique de collaboration",
                "db_table": "coip_collaboration_history",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motif", models.TextField(verbose_name="Motif de la demande")),
                (
                    "destinataire",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Destinataire"
                    ),
                ),
                (
                    "programme_concerne",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Programme / poste concerné",
                    ),
                ),
                (
                    "observations_etudiant",
                    models.TextField(
                        blank=True, verbose_name="Observations de l'étudiant"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDEE", "Validée"),
                            ("EN_REDACTION", "En rédaction"),
                            ("SIGNEE", "Signée"),
                            ("LIVREE", "Livrée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "lettre_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="coip/recommendations/",
                        verbose_name="Lettre (PDF)",
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "date_livraison",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de livraison"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommandations_assignees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignée à",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_requests",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de recommandation",
                "verbose_name_plural": "Demandes de recommandation",
                "db_table": "coip_recommendation_request",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("VALIDEE", "Validée"),
                            ("EN_REDACTION", "En rédaction"),
                            ("SIGNEE", "Signée"),
                            ("LIVREE", "Livrée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_history",
                        to="coip.recommendationrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de workflow (recommandation)",
                "verbose_name_plural": "Historique de workflow (recommandations)",
                "db_table": "coip_recommendation_workflow",
                "ordering": ["changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "type_rapport",
                    models.CharField(
                        choices=[
                            ("MENSUEL", "Mensuel"),
                            ("TRIMESTRIEL", "Trimestriel"),
                            ("ANNUEL", "Annuel"),
                            ("PERSONNALISE", "Personnalisé"),
                        ],
                        default="PERSONNALISE",
                        max_length=15,
                        verbose_name="Type de rapport",
                    ),
                ),
                (
                    "format_fichier",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EXCEL", "Excel")],
                        default="PDF",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                ("periode_debut", models.DateField(verbose_name="Début de période")),
                ("periode_fin", models.DateField(verbose_name="Fin de période")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("GENERE", "Généré"),
                            ("ERREUR", "Erreur"),
                        ],
                        default="EN_ATTENTE",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="coip/reports/",
                        verbose_name="Fichier généré",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de génération"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "genere_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapports_coip_generes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Généré par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport COIP",
                "verbose_name_plural": "Rapports COIP",
                "db_table": "coip_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autorisation",
                    models.BooleanField(
                        default=False,
                        verbose_name="Autorisation parentale/administrative reçue",
                    ),
                ),
                ("present", models.BooleanField(default=False, verbose_name="Présent")),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observations"),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sorties_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="coip.educationalvisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant à la sortie",
                "verbose_name_plural": "Participants aux sorties",
                "db_table": "coip_visit_participant",
            },
        ),
        migrations.CreateModel(
            name="VisitPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="coip/visits/photos/")),
                (
                    "legende",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="coip.educationalvisit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo de sortie",
                "verbose_name_plural": "Photos de sortie",
                "db_table": "coip_visit_photo",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PARTICIPANT", "Participant"),
                            ("INTERVENANT", "Intervenant"),
                            ("ORGANISATEUR", "Organisateur"),
                        ],
                        default="PARTICIPANT",
                        max_length=15,
                        verbose_name="Rôle",
                    ),
                ),
                ("present", models.BooleanField(default=False, verbose_name="Présent")),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="coip.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activites_coip_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant à l'activité",
                "verbose_name_plural": "Participants aux activités",
                "db_table": "coip_activity_participant",
                "unique_together": {("activity", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="alumni",
            index=models.Index(
                fields=["-annee_obtention"], name="coip_alumni_annee_o_bc790a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alumni",
            index=models.Index(
                fields=["secteur_activite"], name="coip_alumni_secteur_998efd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alumni",
            index=models.Index(
                fields=["is_employed"], name="coip_alumni_is_empl_169414_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["categorie"], name="coip_archiv_categor_c4cd5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="archive",
            index=models.Index(
                fields=["-created_at"], name="coip_archiv_created_ce0be0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="educationalvisit",
            index=models.Index(fields=["status"], name="coip_educat_status_7f1fb9_idx"),
        ),
        migrations.AddIndex(
            model_name="educationalvisit",
            index=models.Index(
                fields=["-date_depart"], name="coip_educat_date_de_43f69d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["status"], name="coip_job_ap_status_129885_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("opportunity", "student")},
        ),
        migrations.AddIndex(
            model_name="orientationsession",
            index=models.Index(
                fields=["-date_session"], name="coip_orient_date_se_ab9b79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orientationsession",
            index=models.Index(
                fields=["type_session"], name="coip_orient_type_se_7b2e0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["type_partenaire"], name="coip_partne_type_pa_6ebebb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["is_active"], name="coip_partne_is_acti_946e5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["status"], name="coip_opport_status_c33b04_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["type_opportunite"], name="coip_opport_type_op_f1fcf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["-created_at"], name="coip_opport_created_29a6bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internshipoffer",
            index=models.Index(fields=["status"], name="coip_intern_status_40ef1b_idx"),
        ),
        migrations.AddIndex(
            model_name="internshipoffer",
            index=models.Index(
                fields=["type_stage"], name="coip_intern_type_st_0a204e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(fields=["status"], name="coip_intern_status_c91ffa_idx"),
        ),
        migrations.AddIndex(
            model_name="internship",
            index=models.Index(
                fields=["-date_debut"], name="coip_intern_date_de_335a55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["status"], name="coip_activi_status_4a08f2_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["type_activite"], name="coip_activi_type_ac_9bdd81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["-date_debut"], name="coip_activi_date_de_fd1797_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnership",
            index=models.Index(fields=["status"], name="coip_partne_status_6f3ed9_idx"),
        ),
        migrations.AddIndex(
            model_name="partnership",
            index=models.Index(
                fields=["-date_signature"], name="coip_partne_date_si_9a04ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationrequest",
            index=models.Index(fields=["status"], name="coip_recomm_status_f2b790_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendationrequest",
            index=models.Index(
                fields=["-date_demande"], name="coip_recomm_date_de_91ba4e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visitparticipant",
            unique_together={("visit", "user")},
        ),
    ]
