# Generated by Django 5.1.4 on 2026-06-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_structure", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Intitulé")),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("CM", "Cours magistral"),
                            ("TD", "Travaux dirigés"),
                            ("TP", "Travaux pratiques"),
                        ],
                        default="CM",
                        max_length=5,
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=4,
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "credits",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Crédits ECTS"
                    ),
                ),
                (
                    "volume_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Volume horaire",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="academic_structure.program",
                    ),
                ),
                (
                    "responsible_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_subjects",
                        to="teachers.teacher",
                        verbose_name="Enseignant responsable",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subjects",
                        to="academic_structure.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "db_table": "subjects",
                "ordering": ["code"],
            },
        ),
    ]
