# Generated by Django 5.1.4 on 2026-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0004_subject_volume_total_ue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="credits",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Crédits ECTS"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="volume_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="Volume horaire (CM+TD+TP)",
            ),
        ),
    ]
