# Generated by Django 5.1.4 on 2026-07-11 17:55

import academic_core.apps.subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0005_course_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="syllabus",
            field=models.FileField(
                blank=True,
                help_text="Document de référence fourni à l'enseignant lors de l'attribution de l'EC ; il est tenu de le suivre.",
                null=True,
                upload_to=academic_core.apps.subjects.models._syllabus_upload_path,
                verbose_name="Syllabus",
            ),
        ),
    ]
