# Generated by Django 5.1.4 on 2026-07-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0006_subject_syllabus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["code"],
                "verbose_name": "Module (EC)",
                "verbose_name_plural": "Modules (EC)",
            },
        ),
    ]
