# Generated by Django 5.1.4 on 2026-06-16 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCancellation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_date",
                    models.DateField(verbose_name="Date de la séance concernée"),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("CANCEL", "Annulation"), ("POSTPONE", "Report")],
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_comment", models.TextField(blank=True)),
                (
                    "rescheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Nouvelle date"
                    ),
                ),
                ("rescheduled_start", models.TimeField(blank=True, null=True)),
                ("rescheduled_end", models.TimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rescheduled_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_cancellations",
                        to="rooms.room",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_cancellations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellations",
                        to="timetable.timetableentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annulation/Report de cours",
                "verbose_name_plural": "Annulations/Reports de cours",
                "db_table": "course_cancellations",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "request_type"],
                        name="course_canc_status_6b441a_idx",
                    ),
                    models.Index(
                        fields=["timetable_entry", "session_date"],
                        name="course_canc_timetab_9a6c7b_idx",
                    ),
                ],
            },
        ),
    ]
