# Generated by Django 5.1.4 on 2026-07-18 21:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0033_lignebudgetaire_axe_strategique_and_more"),
        ("accounts", "0032_controllerinstitut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "contact_nom",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom du contact"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "db_table": "achats_fournisseurs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="DemandeAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                ("objet", models.CharField(max_length=255, verbose_name="Objet")),
                (
                    "type_depense",
                    models.CharField(
                        choices=[
                            ("fournitures", "Fournitures"),
                            ("services", "Services"),
                            ("equipement", "Équipement"),
                            ("travaux", "Travaux"),
                            ("autre", "Autre"),
                        ],
                        default="fournitures",
                        max_length=20,
                        verbose_name="Type de dépense",
                    ),
                ),
                (
                    "date_demande",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de demande",
                    ),
                ),
                (
                    "montant_estime",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Montant estimé (FCFA)",
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("soumise", "Soumise"),
                            ("validee", "Validée"),
                            ("rejetee", "Rejetée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif du rejet"),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "centre_cout",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_achat",
                        to="accounts.direction",
                        verbose_name="Centre de coût (Direction)",
                    ),
                ),
                (
                    "demandeur",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_achat",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "ligne_budgetaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_achat",
                        to="accounting.lignebudgetaire",
                        verbose_name="Ligne budgétaire",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_achat_validees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'achat",
                "verbose_name_plural": "Demandes d'achat",
                "db_table": "achats_demandes",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="CommandeAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "date_commande",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de commande",
                    ),
                ),
                (
                    "date_livraison_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison prévue"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "demande_achat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to="procurement.demandeachat",
                        verbose_name="Demande d'achat",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to="procurement.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "db_table": "achats_commandes",
                "ordering": ["-date_commande"],
            },
        ),
        migrations.CreateModel(
            name="AppelOffres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "date_lancement",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de lancement",
                    ),
                ),
                (
                    "date_limite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date limite de dépôt"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("cloture", "Clôturé"),
                            ("attribue", "Attribué"),
                            ("annule", "Annulé"),
                        ],
                        default="ouvert",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "demande_achat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appel_offres",
                        to="procurement.demandeachat",
                        verbose_name="Demande d'achat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appel d'offres",
                "verbose_name_plural": "Appels d'offres",
                "db_table": "achats_appels_offres",
                "ordering": ["-date_lancement"],
            },
        ),
        migrations.CreateModel(
            name="FactureAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_facture",
                    models.CharField(max_length=50, verbose_name="Numéro de facture"),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("validee", "Validée"),
                            ("payee", "Payée"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "piece_jointe",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="achats/factures/%Y/%m/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures",
                        to="procurement.commandeachat",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "db_table": "achats_factures",
                "ordering": ["-created_at"],
                "unique_together": {("commande", "numero_facture")},
            },
        ),
        migrations.CreateModel(
            name="OffreFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_propose",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Montant proposé (FCFA)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("recue", "Reçue"),
                            ("retenue", "Retenue"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="recue",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="achats/offres/%Y/%m/",
                        verbose_name="Document",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appel_offres",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offres",
                        to="procurement.appeloffres",
                        verbose_name="Appel d'offres",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offres",
                        to="procurement.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre fournisseur",
                "verbose_name_plural": "Offres fournisseurs",
                "db_table": "achats_offres_fournisseurs",
                "ordering": ["montant_propose"],
            },
        ),
        migrations.CreateModel(
            name="PaiementAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de paiement",
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                            ("especes", "Espèces"),
                        ],
                        default="virement",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("effectue", "Effectué"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "demande_depense_generee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiement_achat_origine",
                        to="accounting.demandedepense",
                        verbose_name="Demande de dépense générée",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="procurement.factureachat",
                        verbose_name="Facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "db_table": "achats_paiements",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="ReceptionAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_reception",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de réception",
                    ),
                ),
                (
                    "conforme",
                    models.BooleanField(default=True, verbose_name="Conforme"),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receptions",
                        to="procurement.commandeachat",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "recu_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receptions_achat",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reçu par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réception",
                "verbose_name_plural": "Réceptions",
                "db_table": "achats_receptions",
                "ordering": ["-date_reception"],
            },
        ),
    ]
