# Generated by Django 5.1.4 on 2026-07-31 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la ressource"
                    ),
                ),
                (
                    "functionality",
                    models.CharField(
                        choices=[
                            ("ETUDIANTS", "Étudiants"),
                            ("EMARGEMENTS", "Émargements"),
                            ("NOTES", "Notes & Évaluations"),
                            ("ENSEIGNANTS", "Enseignants"),
                            ("PLANNING", "Emploi du temps"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                        verbose_name="Fonctionnalité",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Ce que renvoie cette ressource, et les filtres disponibles (paramètres de requête).",
                        verbose_name="Description",
                    ),
                ),
                (
                    "endpoint_path",
                    models.CharField(
                        help_text="Ex. : /api/v1/students/ — une clé accordée sur cette ressource donne accès à ce chemin et ses sous-chemins.",
                        max_length=300,
                        verbose_name="Chemin de l'API",
                    ),
                ),
                (
                    "http_method",
                    models.CharField(
                        default="GET", max_length=10, verbose_name="Méthode HTTP"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ressource API",
                "verbose_name_plural": "Ressources API",
                "db_table": "api_gateway_resources",
                "ordering": ["functionality", "name"],
            },
        ),
        migrations.CreateModel(
            name="APIAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Besoin exprimé")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, verbose_name="Note de l'administrateur"
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_access_requests_processed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traitée par",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_access_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "suggested_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggested_for_requests",
                        to="api_gateway.apiresource",
                        verbose_name="Ressource suggérée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'accès API",
                "verbose_name_plural": "Demandes d'accès API",
                "db_table": "api_gateway_access_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIAccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_alias",
                    models.CharField(max_length=100, verbose_name="Base tenant"),
                ),
                (
                    "key_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        max_length=16,
                        verbose_name="Préfixe (identification sans exposer la clé)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(default=False, verbose_name="Révoquée"),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_access_grants_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Accordé par",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_access_grants_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_access_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur autorisé",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grants",
                        to="api_gateway.apiaccessrequest",
                        verbose_name="Demande d'origine",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="api_gateway.apiresource",
                        verbose_name="Ressource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès API accordé",
                "verbose_name_plural": "Accès API accordés",
                "db_table": "api_gateway_access_grants",
                "ordering": ["-created_at"],
            },
        ),
    ]
