# Generated by Django 5.1.4 on 2026-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_gateway", "0002_seed_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiresource",
            name="functionality",
            field=models.CharField(
                choices=[
                    ("ETUDIANTS", "Étudiants"),
                    ("EMARGEMENTS", "Émargements"),
                    ("NOTES", "Notes & Évaluations"),
                    ("ENSEIGNANTS", "Enseignants"),
                    ("PLANNING", "Emploi du temps"),
                    ("STRUCTURE", "Structure académique"),
                    ("ROOMS", "Salles & Bâtiments"),
                    ("SUBJECTS", "Matières"),
                    ("CANCELLATIONS", "Annulations de cours"),
                    ("NOTIFICATIONS", "Notifications"),
                    ("ACCOUNTING", "Comptabilité"),
                    ("HR", "Ressources Humaines"),
                    ("COMMUNITY", "Service à la communauté"),
                    ("STRATEGIC", "Plan stratégique"),
                    ("INDICATORS", "Indicateurs"),
                    ("PROCUREMENT", "Achats"),
                    ("QUALITY", "Qualité"),
                    ("RISKS", "Risques"),
                    ("COIP", "COIP"),
                    ("ADMISSIONS", "Admissions"),
                    ("AUTRE", "Autre"),
                ],
                default="AUTRE",
                max_length=20,
                verbose_name="Fonctionnalité",
            ),
        ),
    ]
