# Generated by Django 5.1.4 on 2026-07-30 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityServiceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("SENSIBILISATION", "Sensibilisation"),
                            ("FORMATION", "Formation / Atelier"),
                            ("SOLIDARITE", "Don / Solidarité"),
                            ("PARTENARIAT", "Partenariat communautaire"),
                            ("BENEVOLAT", "Bénévolat"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "lieu",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "beneficiaires",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Bénéficiaires"
                    ),
                ),
                (
                    "nombre_participants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de participants"
                    ),
                ),
                (
                    "partenaires",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Partenaires associés"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIEE", "Planifiée"),
                            ("REALISEE", "Réalisée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="PLANIFIEE",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "resultats",
                    models.TextField(blank=True, verbose_name="Résultats / Bilan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites_communautaires_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites_communautaires",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable de l'activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité de service à la communauté",
                "verbose_name_plural": "Activités de service à la communauté",
                "db_table": "community_service_activity",
                "ordering": ["-date_debut"],
                "indexes": [
                    models.Index(
                        fields=["-date_debut"], name="community_s_date_de_20dca3_idx"
                    ),
                    models.Index(
                        fields=["categorie"], name="community_s_categor_9a8f48_idx"
                    ),
                    models.Index(
                        fields=["statut"], name="community_s_statut_3a90df_idx"
                    ),
                ],
            },
        ),
    ]
