# Generated by Django 5.1.4 on 2026-06-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0004_student_extended_fields"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="current_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_students",
                to="academic_structure.class",
                verbose_name="Classe",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_address",
            field=models.TextField(blank=True, verbose_name="Adresse tuteur"),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email tuteur"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_first_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Prénom tuteur"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom tuteur"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AddField(
            model_name="student",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                max_length=1,
                verbose_name="Genre",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Tuteur (ancien)"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="guardian_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Téléphone tuteur"
            ),
        ),
    ]
