# Generated by Django 5.1.4 on 2026-06-19 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0006_add_bulletin_config"),
        ("students", "0002_student_extended_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "ordering": ["-enrollment_date"],
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrollment_type",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle inscription"),
                    ("REINSCRIPTION", "Réinscription"),
                ],
                default="NEW",
                max_length=20,
                verbose_name="Type d'inscription",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observations"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant payé (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de paiement"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Référence paiement"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="previous_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="past_students",
                to="academic_structure.class",
                verbose_name="Classe précédente",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("VALIDATED", "Validée"),
                    ("REJECTED", "Rejetée"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de validation"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validé par",
            ),
        ),
    ]
