# Generated by Django 5.1.4 on 2026-06-19 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_enrollment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="monthly_installment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant fixe à verser chaque mois pour solder le restant dû",
                max_digits=12,
                null=True,
                verbose_name="Versement mensuel (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="total_fees",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais totaux (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant versé (FCFA)",
            ),
        ),
        migrations.CreateModel(
            name="PaymentInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveSmallIntegerField(verbose_name="N° échéance"),
                ),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "amount_expected",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Montant dû (FCFA)",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Montant reçu (FCFA)",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Réglée")),
                ("notes", models.TextField(blank=True, verbose_name="Observations")),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="students.enrollment",
                        verbose_name="Inscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Échéance de paiement",
                "verbose_name_plural": "Échéances de paiement",
                "db_table": "payment_installments",
                "ordering": ["due_date"],
                "unique_together": {("enrollment", "installment_number")},
            },
        ),
    ]
