# Generated by Django 5.1.4 on 2026-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_add_fees_installment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="payment_suspended",
            field=models.BooleanField(
                default=False, verbose_name="Suspendu pour impayé"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="suspension_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de suspension"
            ),
        ),
    ]
