# Generated by Django 5.1.4 on 2026-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_add_payment_suspended_to_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="frais_generaux",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais généraux (FCFA)",
            ),
        ),
    ]
