# Generated by Django 5.1.4 on 2026-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_fix_cross_db_fk_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="students/photos/",
                verbose_name="Photo",
            ),
        ),
    ]
