# Generated by Django 5.1.4 on 2026-06-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_add_photo_to_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="advance_months",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Mois payés en avance",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("PENDING_CAISSE", "En attente caisse"),
                    ("VALIDATED", "Validée"),
                    ("REJECTED", "Rejetée"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
