# Generated by Django 5.1.4 on 2026-07-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0019_alter_fraismensuelclasse_options_and_more"),
        ("students", "0009_add_pending_caisse_advance_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_boursier",
            field=models.BooleanField(default=False, verbose_name="Étudiant boursier"),
        ),
        migrations.AddField(
            model_name="student",
            name="partenaire_bourse",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="etudiants_boursiers",
                to="accounting.partenairebourse",
                verbose_name="Partenaire de bourse",
            ),
        ),
    ]
