# Generated by Django 5.1.4 on 2026-07-02 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_student_is_boursier_student_partenaire_bourse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="credit_report",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Montant déjà payé lors d'une inscription suspendue, reporté sur cette réinscription.",
                max_digits=12,
                verbose_name="Crédit reporté (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'abandon/suspension"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status_changed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_changed_enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Enregistré par",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status_reason",
            field=models.TextField(
                blank=True, verbose_name="Motif d'abandon/suspension"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("PENDING_CAISSE", "En attente caisse"),
                    ("VALIDATED", "Validée"),
                    ("REJECTED", "Rejetée"),
                    ("ABANDONED", "Abandon"),
                    ("SUSPENDED", "Suspension d'inscription"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
