# Generated by Django 5.1.4 on 2026-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_enrollment_credit_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_type",
            field=models.CharField(
                choices=[
                    ("NEW", "Nouvelle inscription"),
                    ("REINSCRIPTION", "Réinscription"),
                    ("CHANGE_FILIERE", "Changement de filière"),
                ],
                default="NEW",
                max_length=20,
                verbose_name="Type d'inscription",
            ),
        ),
    ]
