# Generated by Django 5.1.4 on 2026-07-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_alter_enrollment_enrollment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="frais_amea",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais AMEA (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="frais_assurance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais d'assurance (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="frais_bibliotheque",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais Bibliothèque (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="frais_soutenance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais de soutenance normal (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="frais_soutenance_speciale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais de soutenance spéciale (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="frais_tenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais de tenue (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="advance_months",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="Mois payés en avance",
            ),
        ),
    ]
