# Generated by Django 5.1.4 on 2026-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_enrollment_frais_amea_enrollment_frais_assurance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="frais_amea",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Frais Amicale (FCFA)",
            ),
        ),
    ]
