# Generated by Django 5.1.4 on 2026-07-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_alter_enrollment_frais_amea"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="bourse_pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Pourcentage à payer (boursier)",
            ),
        ),
    ]
