# Generated by Django 5.1.4 on 2026-07-04 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_enrollment_bourse_pourcentage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="bourse_deadline",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Échéance de régularisation (partenaire)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="bourse_regularisation_notes",
            field=models.TextField(
                blank=True, verbose_name="Observations (régularisation)"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="bourse_regularized",
            field=models.BooleanField(default=False, verbose_name="Régularisé"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="bourse_regularized_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant régularisé (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="bourse_regularized_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bourse_regularisations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Régularisé par",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="bourse_regularized_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de régularisation"
            ),
        ),
        migrations.AddField(
            model_name="paymentinstallment",
            name="prepared_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Préparée le"
            ),
        ),
        migrations.AddField(
            model_name="paymentinstallment",
            name="prepared_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prepared_installments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Préparée par (Trésorier Général)",
            ),
        ),
    ]
