# Generated by Django 5.1.4 on 2026-07-12 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_enrollment_bourse_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_rep_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_reps_appointed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nommé par",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="class_rep_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Aucun"),
                    ("RESPONSABLE", "Responsable de classe"),
                    ("ADJOINT", "Adjoint du responsable de classe"),
                ],
                default="",
                help_text="Un étudiant nommé responsable ou adjoint de sa classe peut consulter et valider le cahier de texte de cette classe, en plus de ses droits d'étudiant.",
                max_length=15,
                verbose_name="Rôle de représentation de classe",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="class_rep_since",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Nommé le"),
        ),
    ]
