# Generated by Django 5.1.4 on 2026-06-16 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_structure", "0001_initial"),
        ("students", "0001_initial"),
        ("subjects", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("CC", "Contrôle continu"),
                            ("TP", "Travaux pratiques"),
                            ("PROJECT", "Projet"),
                            ("EXAM", "Examen final"),
                            ("RATTRAPAGE", "Rattrapage"),
                        ],
                        max_length=15,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Coefficient de pondération",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Type d'évaluation",
                "db_table": "evaluation_types",
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Intitulé")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="Note maximale",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, verbose_name="Notes verrouillées"
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="academic_structure.semester",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="teachers.teacher",
                    ),
                ),
                (
                    "evaluation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="grades.evaluationtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
                "db_table": "evaluations",
                "ordering": ["semester", "subject", "date"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Note",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="grades.evaluation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "db_table": "grades",
                "indexes": [
                    models.Index(
                        fields=["student", "evaluation"],
                        name="grades_student_673ef2_idx",
                    )
                ],
                "unique_together": {("student", "evaluation")},
            },
        ),
        migrations.CreateModel(
            name="SemesterAverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "total_students",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("mention", models.CharField(blank=True, max_length=50)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_averages",
                        to="academic_structure.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_averages",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moyenne semestrielle",
                "db_table": "semester_averages",
                "unique_together": {("student", "semester")},
            },
        ),
        migrations.CreateModel(
            name="SubjectAverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_validated", models.BooleanField(default=False)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_averages",
                        to="academic_structure.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_averages",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_averages",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moyenne matière",
                "db_table": "subject_averages",
                "unique_together": {("student", "subject", "semester")},
            },
        ),
    ]
