# Generated by Django 5.1.4 on 2026-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_seed_evaluation_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationtype",
            name="code",
            field=models.CharField(
                choices=[
                    ("CC", "Contrôle continu"),
                    ("TP", "Travaux pratiques"),
                    ("PROJECT", "Projet"),
                    ("EXAM", "Examen final"),
                    ("RATTRAPAGE", "Rattrapage"),
                    ("DEVOIR1", "Devoir 1"),
                    ("DEVOIR2", "Devoir 2"),
                ],
                max_length=15,
                unique=True,
            ),
        ),
    ]
