# Generated by Django 5.1.4 on 2026-07-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0007_ecvalidation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectaverage",
            options={"verbose_name": "Moyenne module (EC)"},
        ),
    ]
