# Generated by Django 5.1.4 on 2026-07-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0008_alter_subjectaverage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulletinecresult",
            options={"ordering": ["subject__code"]},
        ),
    ]
