# Generated by Django 5.1.4 on 2026-07-25 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0029_department_admissions_date_fermeture_and_more"),
        ("grades", "0009_alter_bulletinecresult_options"),
        ("students", "0018_student_country_of_birth_student_nationality"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Motif de la réclamation"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Traitée le"),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_complaints",
                        to="academic_structure.class",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_complaints_processed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traitée par",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_complaints",
                        to="academic_structure.semester",
                        verbose_name="Semestre",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_complaints",
                        to="students.student",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réclamation de note",
                "verbose_name_plural": "Réclamations de notes",
                "db_table": "grade_complaints",
                "ordering": ["-processed_at"],
            },
        ),
    ]
