# Generated by Django 5.1.4 on 2026-06-16 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="admin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administered_department",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administrateur de département",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
    ]
