# Generated by Django 5.1.4 on 2026-06-16 17:02

from django.db import migrations


def seed_faculty(apps, schema_editor):
    Faculty = apps.get_model('academic_structure', 'Faculty')
    Faculty.objects.get_or_create(
        code='ISI',
        defaults={'name': "Institut Supérieur d'Informatique"},
    )


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0002_department_admin_department_description_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_faculty, reverse_seed),
    ]
