# Generated by Django 5.1.4 on 2026-06-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0003_seed_faculty_isi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Institut", "verbose_name_plural": "Instituts"},
        ),
    ]
