# Generated by Django 5.1.4 on 2026-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0004_student_extended_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="domaine",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Domaine"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="mention",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Mention"
            ),
        ),
    ]
