# Generated by Django 5.1.4 on 2026-06-19 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0005_add_domaine_mention_to_class"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletinConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "director_title",
                    models.CharField(
                        default="Directrice des études",
                        max_length=200,
                        verbose_name="Titre du signataire",
                    ),
                ),
                (
                    "director_name",
                    models.CharField(
                        default="", max_length=200, verbose_name="Nom du signataire"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulletin_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration bulletin",
                "db_table": "bulletin_config",
            },
        ),
    ]
