# Generated by Django 5.1.4 on 2026-06-20 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0006_add_bulletin_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        default="",
                        max_length=300,
                        verbose_name="Nom de l'établissement",
                    ),
                ),
                (
                    "sigle",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sigle / Acronyme"
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Devise / Slogan"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institut/logos/",
                        verbose_name="Logo principal",
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Sénégal", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email institutionnel"
                    ),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "annee_creation",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Année de création"
                    ),
                ),
                (
                    "numero_autorisation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="N° d'autorisation"
                    ),
                ),
                (
                    "statut_juridique",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Statut juridique"
                    ),
                ),
                (
                    "dg_titre",
                    models.CharField(
                        blank=True,
                        default="Directeur Général",
                        max_length=200,
                        verbose_name="Titre DG",
                    ),
                ),
                (
                    "dg_nom",
                    models.CharField(blank=True, max_length=200, verbose_name="Nom DG"),
                ),
                (
                    "de_titre",
                    models.CharField(
                        blank=True,
                        default="Directeur des Études",
                        max_length=200,
                        verbose_name="Titre DE",
                    ),
                ),
                (
                    "de_nom",
                    models.CharField(blank=True, max_length=200, verbose_name="Nom DE"),
                ),
                (
                    "couleur_primaire",
                    models.CharField(
                        default="#00173B",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(
                        default="#D4AF37",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institut_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration établissement",
                "db_table": "institut_config",
            },
        ),
        migrations.CreateModel(
            name="InstitutFiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=300, verbose_name="Nom")),
                (
                    "type_filiation",
                    models.CharField(
                        choices=[
                            ("TUTELLE", "Tutelle / Ministère"),
                            ("PARTENAIRE", "Partenaire"),
                            ("ACCREDITATION", "Accréditation"),
                            ("RESEAU", "Réseau / Association"),
                        ],
                        default="TUTELLE",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="institut/filiations/",
                        verbose_name="Logo",
                    ),
                ),
                ("site_web", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Affiché")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filiations",
                        to="academic_structure.institutconfig",
                        verbose_name="Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filiation",
                "verbose_name_plural": "Filiations",
                "db_table": "institut_filiations",
                "ordering": ["ordre", "nom"],
            },
        ),
    ]
