# Generated by Django 5.1.4 on 2026-06-20 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0007_institut_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutconfig",
            name="actif",
            field=models.BooleanField(default=True, verbose_name="Institut actif"),
        ),
        migrations.AddField(
            model_name="institutconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="institutconfig",
            name="date_suspension",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de suspension"
            ),
        ),
        migrations.AddField(
            model_name="institutconfig",
            name="faculty",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institut_config",
                to="academic_structure.faculty",
                verbose_name="Faculté / Entité parente",
            ),
        ),
        migrations.AddField(
            model_name="institutconfig",
            name="motif_suspension",
            field=models.TextField(blank=True, verbose_name="Motif de suspension"),
        ),
    ]
