# Generated by Django 5.1.4 on 2026-06-20 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0008_institut_actif_faculty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbonnementInstitut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date de debut")),
                (
                    "duree_annees",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Nombre d annees de l abonnement (1, 2, 3...)",
                        verbose_name="Duree (annees)",
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(editable=False, verbose_name="Date d expiration"),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant (FCFA)"
                    ),
                ),
                (
                    "reference_paiement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reference de paiement"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("EXPIRE", "Expire"),
                            ("SUSPENDU", "Suspendu"),
                            ("EN_ATTENTE", "En attente de paiement"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements",
                        to="academic_structure.institutconfig",
                        verbose_name="Etablissement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abonnements_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cree par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement institut",
                "verbose_name_plural": "Abonnements instituts",
                "db_table": "abonnements_instituts",
                "ordering": ["-date_debut"],
            },
        ),
    ]
