# Generated by Django 5.1.4 on 2026-06-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0009_abonnement_institut"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="academic_structure.faculty",
                verbose_name="Institut",
            ),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="label",
            field=models.CharField(max_length=20, verbose_name="Libellé"),
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("faculty", "label")},
        ),
    ]
