# Generated by Django 5.1.4 on 2026-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0010_academicyear_faculty_alter_academicyear_label_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="institutconfig",
            name="db_alias",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ex: db_inst_isi — généré automatiquement à la création",
                max_length=60,
                verbose_name="Alias base de données",
            ),
        ),
    ]
