# Generated by Django 5.1.4 on 2026-06-24 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0013_abonnement_rappels_envoyes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="session_normale_closed",
            field=models.BooleanField(
                default=False, verbose_name="Session normale clôturée"
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="session_normale_closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Clôturée le"
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="session_normale_closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="semesters_closed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Clôturée par",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="session_rattrapage_active",
            field=models.BooleanField(
                default=False, verbose_name="Session rattrapage active"
            ),
        ),
    ]
