# Generated by Django 5.1.4 on 2026-06-24 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0014_semester_session_cloture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="session_normale_closed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="semesters_closed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Clôturée par",
            ),
        ),
    ]
