# Generated by Django 5.1.4 on 2026-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0015_fix_semester_closed_by_no_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutconfig",
            name="matricule_prefix",
            field=models.CharField(
                blank=True,
                default="411",
                help_text="Préfixe fixe du matricule étudiant. Ex : 411 → 411-26-1234/ISI",
                max_length=20,
                verbose_name="Préfixe matricule",
            ),
        ),
    ]
