# Generated by Django 5.1.4 on 2026-07-03 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0016_add_matricule_prefix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="is_locked",
            field=models.BooleanField(
                default=False, verbose_name="Semestre verrouillé"
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="locked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Verrouillé le"
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="semesters_locked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verrouillé par",
            ),
        ),
    ]
