# Generated by Django 5.1.4 on 2026-07-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0017_semester_is_locked_semester_locked_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="semester",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="semesters",
                to="academic_structure.level",
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("academic_year", "number", "level")},
        ),
    ]
