# Generated by Django 5.1.4 on 2026-07-12 15:30

import django.db.models.deletion
from django.db import migrations, models


def seed_default_articles(apps, schema_editor):
    # InstitutConfig / ContratArticle sont des modèles "master" (voir
    # db_router.MASTER_MODEL_NAMES) : ils ne vivent que dans la base 'default',
    # même si cette migration (app academic_structure, non "master app") est
    # rejouée sur chaque base institut lors de `manage.py migrate`. On ignore
    # donc les passages sur les autres alias pour ne pas dupliquer les articles
    # dans des tables tenant qui ne sont jamais lues par l'application.
    if schema_editor.connection.alias != 'default':
        return

    from academic_core.apps.academic_structure.models import DEFAULT_CONTRAT_ARTICLES

    InstitutConfig  = apps.get_model('academic_structure', 'InstitutConfig')
    ContratArticle  = apps.get_model('academic_structure', 'ContratArticle')

    for config in InstitutConfig.objects.using('default').all():
        if ContratArticle.objects.using('default').filter(config=config).exists():
            continue
        ContratArticle.objects.using('default').bulk_create([
            ContratArticle(config=config, numero=numero, texte=texte)
            for numero, texte in DEFAULT_CONTRAT_ARTICLES
        ])


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic_structure",
            "0018_alter_semester_unique_together_semester_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="institutconfig",
            name="contrat_article1_texte",
            field=models.TextField(
                blank=True,
                default="le prestataire s'engage, dans le respect du manuel de procédures pédagogiques et du règlement intérieur de l'établissement, à dispenser des enseignements pour la période : {periode}. Les enseignements portent sur les modules suivants :",
                help_text="Le repère {periode} est remplacé automatiquement par l’année académique du contrat.",
                verbose_name="Article 1 — texte d'introduction",
            ),
        ),
        migrations.AddField(
            model_name="institutconfig",
            name="contrat_cahier_charge_texte",
            field=models.TextField(
                blank=True,
                default="Les modalités d'exécution de la prestation et les objectifs fixés à atteindre sont définis dans un cahier de charge qui sera remis au prestataire. Ledit cahier de charge lie le prestataire.",
                verbose_name="Paragraphe « cahier de charge »",
            ),
        ),
        migrations.AddField(
            model_name="institutconfig",
            name="contrat_titre",
            field=models.CharField(
                blank=True,
                default="CONTRAT DE PRESTATION DE SERVICE",
                max_length=200,
                verbose_name="Titre du contrat",
            ),
        ),
        migrations.CreateModel(
            name="ContratArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField(verbose_name="Numéro")),
                ("texte", models.TextField(verbose_name="Texte")),
                (
                    "actif",
                    models.BooleanField(
                        default=True, verbose_name="Inclus dans le contrat"
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrat_articles",
                        to="academic_structure.institutconfig",
                        verbose_name="Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de contrat",
                "verbose_name_plural": "Articles de contrat",
                "db_table": "contrat_articles",
                "ordering": ["numero"],
            },
        ),
        migrations.RunPython(seed_default_articles, migrations.RunPython.noop),
    ]
