# Generated by Django 5.1.4 on 2026-07-15 20:33

import django.db.models.deletion
from django.db import migrations, models


def disable_fk(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.connection.cursor().execute("PRAGMA foreign_keys = OFF")


def enable_fk(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.connection.cursor().execute("PRAGMA foreign_keys = ON")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("academic_structure", "0019_institutconfig_contrat_article1_texte_and_more"),
    ]

    operations = [
        migrations.RunPython(disable_fk, reverse_code=enable_fk),
        migrations.AlterField(
            model_name="academicyear",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="academic_structure.faculty",
                verbose_name="Institut",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="academic_structure.faculty",
            ),
        ),
        migrations.RunPython(enable_fk, reverse_code=disable_fk),
    ]
