# Generated by Django 5.1.4 on 2026-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0020_fix_faculty_institutconfig_cross_db_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="level",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Niveau"
            ),
        ),
    ]
