# Generated by Django 5.1.4 on 2026-07-17 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0021_program_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutDisabledFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tab_key",
                    models.CharField(max_length=50, verbose_name="Onglet parent"),
                ),
                (
                    "feature_key",
                    models.CharField(max_length=100, verbose_name="Fonctionnalité"),
                ),
                ("disabled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institut_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabled_features",
                        to="academic_structure.institutconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fonctionnalité désactivée",
                "verbose_name_plural": "Fonctionnalités désactivées",
                "db_table": "institut_disabled_features",
                "unique_together": {("institut_config", "feature_key")},
            },
        ),
        migrations.CreateModel(
            name="InstitutDisabledTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tab_key", models.CharField(max_length=50, verbose_name="Onglet")),
                ("disabled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "disabled_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institut_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabled_tabs",
                        to="academic_structure.institutconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onglet désactivé",
                "verbose_name_plural": "Onglets désactivés",
                "db_table": "institut_disabled_tabs",
                "unique_together": {("institut_config", "tab_key")},
            },
        ),
    ]
