# Generated by Django 5.1.4 on 2026-07-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0022_institutdisabledfeature_institutdisabledtab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutconfig",
            name="actif",
            field=models.BooleanField(default=False, verbose_name="Institut actif"),
        ),
    ]
