# Generated by Django 5.1.4 on 2026-07-19 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0023_alter_institutconfig_actif"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedInstitutDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de l'institut"),
                ),
                ("sigle", models.CharField(blank=True, max_length=30)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Recréer un institut avec ce même code régénère le même alias de base.",
                        max_length=30,
                        verbose_name="Code Faculty",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        max_length=60, verbose_name="Alias base de données"
                    ),
                ),
                (
                    "archived_path",
                    models.CharField(
                        max_length=255, verbose_name="Chemin du fichier archivé"
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Supprimée définitivement le",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Base d'institut archivée",
                "verbose_name_plural": "Bases d'instituts archivées",
                "db_table": "archived_institut_databases",
                "ordering": ["-archived_at"],
            },
        ),
    ]
