# Generated by Django 5.1.4 on 2026-07-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0024_archivedinstitutdatabase"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutconfig",
            name="informations_paiement",
            field=models.TextField(
                blank=True,
                help_text="Coordonnées affichées au candidat pour régler ses frais d'inscription (numéros Wave/Orange Money, RIB pour virement, etc.).",
                verbose_name="Informations de paiement",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="competences",
            field=models.TextField(blank=True, verbose_name="Compétences visées"),
        ),
        migrations.AddField(
            model_name="program",
            name="debouches",
            field=models.TextField(blank=True, verbose_name="Débouchés"),
        ),
        migrations.AddField(
            model_name="program",
            name="modalites_admission",
            field=models.TextField(blank=True, verbose_name="Modalités d'admission"),
        ),
        migrations.AddField(
            model_name="program",
            name="objectifs",
            field=models.TextField(
                blank=True, verbose_name="Objectifs de la formation"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="ouvert_admissions",
            field=models.BooleanField(
                default=True,
                help_text="Décoché, la filière disparaît du portail public de candidature.",
                verbose_name="Ouvert aux candidatures",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="places_disponibles",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Laisser vide pour un nombre de places illimité.",
                null=True,
                verbose_name="Places disponibles",
            ),
        ),
        migrations.AlterField(
            model_name="institutconfig",
            name="db_alias",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ex: db_rytal_isi — généré automatiquement à la création",
                max_length=60,
                verbose_name="Alias base de données",
            ),
        ),
    ]
