# Generated by Django 5.1.4 on 2026-07-22 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0025_institutconfig_informations_paiement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutEmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Si activé, les notifications de cet institut sont envoyées via ces paramètres au lieu de la configuration email globale de la plateforme.",
                        verbose_name="Utiliser cette configuration",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Serveur SMTP"
                    ),
                ),
                (
                    "email_port",
                    models.PositiveIntegerField(default=587, verbose_name="Port SMTP"),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=True, verbose_name="Utiliser TLS"),
                ),
                (
                    "email_host_user",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Utilisateur SMTP"
                    ),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Mot de passe SMTP"
                    ),
                ),
                (
                    "default_from_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Adresse d'expédition"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institut_config",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_config",
                        to="academic_structure.institutconfig",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institut_email_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration email institut",
                "verbose_name_plural": "Configurations email instituts",
                "db_table": "institut_email_configs",
            },
        ),
    ]
