# Generated by Django 5.1.4 on 2026-07-22 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0026_institutemailconfig"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutPaymentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Si activé, le candidat voit une option de paiement en ligne (Wave, Orange Money, carte, virement) en plus du dépôt manuel de preuve de paiement.",
                        verbose_name="Activer le paiement en ligne",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            (
                                "PAYDUNYA",
                                "PayDunya (Wave, Orange Money, carte, virement)",
                            )
                        ],
                        default="PAYDUNYA",
                        max_length=20,
                        verbose_name="Agrégateur de paiement",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("TEST", "Test / Sandbox"), ("LIVE", "Production")],
                        default="TEST",
                        max_length=10,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "master_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Master Key"
                    ),
                ),
                (
                    "private_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Private Key"
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Public Key"
                    ),
                ),
                (
                    "token",
                    models.CharField(blank=True, max_length=255, verbose_name="Token"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institut_config",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_config",
                        to="academic_structure.institutconfig",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institut_payment_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration paiement institut",
                "verbose_name_plural": "Configurations paiement instituts",
                "db_table": "institut_payment_configs",
            },
        ),
    ]
