# Generated by Django 5.1.4 on 2026-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0027_institutpaymentconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="presentation_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="academic_structure/departments/presentation/%Y/%m/",
                verbose_name="Image de présentation",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="presentation_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="academic_structure/departments/presentation/%Y/%m/",
                verbose_name="Vidéo de présentation",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="presentation_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="academic_structure/programs/presentation/%Y/%m/",
                verbose_name="Image de présentation",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="presentation_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="academic_structure/programs/presentation/%Y/%m/",
                verbose_name="Vidéo de présentation",
            ),
        ),
    ]
