# Generated by Django 5.1.4 on 2026-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0028_department_presentation_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="admissions_date_fermeture",
            field=models.DateField(
                blank=True,
                help_text="Non définie = pas de limite de ce côté (jamais de fermeture automatique).",
                null=True,
                verbose_name="Date de fermeture des inscriptions",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="admissions_date_ouverture",
            field=models.DateField(
                blank=True,
                help_text="Non définie = pas de limite de ce côté (ouvert dès maintenant).",
                null=True,
                verbose_name="Date d'ouverture des inscriptions",
            ),
        ),
    ]
