# Generated by Django 5.1.4 on 2026-07-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0029_department_admissions_date_fermeture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institutpaymentconfig",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="institutpaymentconfig",
            name="master_key",
        ),
        migrations.RemoveField(
            model_name="institutpaymentconfig",
            name="mode",
        ),
        migrations.RemoveField(
            model_name="institutpaymentconfig",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="institutpaymentconfig",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="institutpaymentconfig",
            name="public_key",
        ),
        migrations.RemoveField(
            model_name="institutpaymentconfig",
            name="token",
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="banque_iban",
            field=models.CharField(blank=True, max_length=50, verbose_name="IBAN"),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="banque_nom",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nom de la banque"
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="banque_rib",
            field=models.CharField(blank=True, max_length=50, verbose_name="RIB"),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="banque_swift",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Code SWIFT/BIC"
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="banque_titulaire",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Titulaire du compte"
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="om_active",
            field=models.BooleanField(
                default=False, verbose_name="Activer Orange Money"
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="om_client_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Client ID"
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="om_client_secret",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Client Secret"
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="om_merchant_key",
            field=models.CharField(
                blank=True,
                help_text="Clé marchand (Merchant Key) fournie par Orange Money.",
                max_length=255,
                verbose_name="Merchant Key",
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="om_mode",
            field=models.CharField(
                choices=[("TEST", "Test / Sandbox"), ("LIVE", "Production")],
                default="TEST",
                max_length=10,
                verbose_name="Mode Orange Money",
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="om_region",
            field=models.CharField(
                default="sn",
                help_text="Code pays utilisé dans l'URL de l'API Orange Money (ex. « sn » pour le Sénégal).",
                max_length=5,
                verbose_name="Code pays Orange Money",
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="virement_active",
            field=models.BooleanField(
                default=False, verbose_name="Activer le virement bancaire"
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="virement_instructions",
            field=models.TextField(
                blank=True, verbose_name="Instructions complémentaires"
            ),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="wave_active",
            field=models.BooleanField(default=False, verbose_name="Activer Wave"),
        ),
        migrations.AddField(
            model_name="institutpaymentconfig",
            name="wave_api_key",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Clé API Wave"
            ),
        ),
    ]
