# Generated by Django 5.1.4 on 2026-07-30 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0030_remove_institutpaymentconfig_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiplomaSupplementConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domaine",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : Sciences et technologies. Si vide, repris du champ « Domaine » de la classe la plus récente de la filière.",
                        max_length=200,
                        verbose_name="Domaine",
                    ),
                ),
                (
                    "langue_etudes",
                    models.CharField(
                        blank=True,
                        default="Le français",
                        max_length=100,
                        verbose_name="Langue d'études",
                    ),
                ),
                (
                    "definition_qualification",
                    models.TextField(
                        blank=True,
                        help_text="Ce que le diplômé est capable de faire — compétences et champ professionnel visés.",
                        verbose_name="Définition de la qualification",
                    ),
                ),
                (
                    "duree_texte",
                    models.CharField(
                        blank=True,
                        help_text="Ex. : « 2 années universitaires après l'obtention de la licence ».",
                        max_length=300,
                        verbose_name="Durée",
                    ),
                ),
                (
                    "conditions_admission",
                    models.TextField(
                        blank=True,
                        help_text="Une condition par ligne — chaque ligne devient une puce du document.",
                        verbose_name="Conditions d'admission",
                    ),
                ),
                (
                    "poursuite_etudes",
                    models.TextField(blank=True, verbose_name="Poursuite d'études"),
                ),
                (
                    "statut_professionnel",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Statut professionnel conféré",
                    ),
                ),
                (
                    "forme_etudes",
                    models.CharField(
                        blank=True,
                        default="En présentiel",
                        max_length=100,
                        verbose_name="Forme des études",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diploma_supplement_config",
                        to="academic_structure.program",
                        verbose_name="Filière",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diploma_supplement_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration supplément de diplôme",
                "verbose_name_plural": "Configurations supplément de diplôme",
                "db_table": "diploma_supplement_configs",
            },
        ),
    ]
