# Generated by Django 5.1.4 on 2026-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("RESPONSABLE", "Administrateur de département"),
                    ("ASSISTANTE", "Assistante de département"),
                    ("ENSEIGNANT", "Enseignant"),
                    ("ETUDIANT", "Étudiant"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
