# Generated by Django 5.1.4 on 2026-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_assistante_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Si actif, l'utilisateur sera forcé de changer son mot de passe à la prochaine connexion.",
                verbose_name="Doit changer son mot de passe",
            ),
        ),
    ]
