# Generated by Django 5.1.4 on 2026-06-19 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_role_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "period_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Période début"
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Période fin"
                    ),
                ),
                (
                    "entries_count",
                    models.PositiveIntegerField(default=0, verbose_name="Nb entrées"),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="Fichier")),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Taille (octets)"
                    ),
                ),
                ("is_auto", models.BooleanField(default=False, verbose_name="Auto")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_backups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sauvegarde d'audit",
                "verbose_name_plural": "Sauvegardes d'audit",
                "db_table": "audit_backups",
                "ordering": ["-created_at"],
            },
        ),
    ]
