# Generated by Django 5.1.4 on 2026-06-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_add_direction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="direction",
        ),
        migrations.AddField(
            model_name="role",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles",
                to="accounts.direction",
                verbose_name="Direction",
            ),
        ),
    ]
