# Generated by Django 5.1.4 on 2026-06-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_direction_to_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="direction",
        ),
        migrations.AddField(
            model_name="role",
            name="directions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                to="accounts.direction",
                verbose_name="Directions",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("ADMIN_DIRECTION", "Administrateur de direction"),
                    ("CIAQ", "CIAQ"),
                    ("CONTROLEUR", "Contrôleur Interne"),
                    ("RESPONSABLE", "Administrateur de département"),
                    ("ASSISTANTE", "Assistante de département"),
                    ("COMPTABLE", "Comptable"),
                    ("ENSEIGNANT", "Enseignant"),
                    ("ETUDIANT", "Étudiant"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
