# Generated by Django 5.1.4 on 2026-06-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0009_abonnement_institut"),
        ("accounts", "0012_role_directions_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institut_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admins",
                to="academic_structure.institutconfig",
                verbose_name="Institut administré",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("INST_ADMIN", "Administrateur d'institut"),
                    ("ADMIN_DIRECTION", "Administrateur de direction"),
                    ("CIAQ", "CIAQ"),
                    ("CONTROLEUR", "Contrôleur Interne"),
                    ("RESPONSABLE", "Administrateur de département"),
                    ("ASSISTANTE", "Assistante de département"),
                    ("COMPTABLE", "Comptable"),
                    ("ENSEIGNANT", "Enseignant"),
                    ("ETUDIANT", "Étudiant"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
