# Generated by Django 5.1.4 on 2026-06-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0009_abonnement_institut"),
        ("accounts", "0013_add_inst_admin_role_and_user_institut_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="direction",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directions",
                to="academic_structure.faculty",
                verbose_name="Institut",
            ),
        ),
        migrations.AlterField(
            model_name="direction",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nom"),
        ),
        migrations.AlterUniqueTogether(
            name="direction",
            unique_together={("faculty", "name")},
        ),
    ]
