# Generated by Django 5.1.4 on 2026-06-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_direction_faculty_alter_direction_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="accounts.direction",
                verbose_name="Direction",
            ),
        ),
    ]
