# Generated by Django 5.1.4 on 2026-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_user_direction_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("INST_ADMIN", "Administrateur d'institut"),
                    ("ASSISTANTE_DG", "Assistante du Directeur Général"),
                    ("ADMIN_DIRECTION", "Administrateur de direction"),
                    ("ASSISTANTE_DIRECTION", "Assistante de Direction"),
                    ("CIAQ", "CIAQ"),
                    ("CONTROLEUR", "Contrôleur Interne"),
                    ("RESPONSABLE", "Administrateur de département"),
                    ("ASSISTANTE", "Assistante de département"),
                    ("COMPTABLE", "Comptable"),
                    ("ENSEIGNANT", "Enseignant"),
                    ("ETUDIANT", "Étudiant"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
