# Generated by Django 5.1.4 on 2026-06-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_add_si_admin_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="matricule_employe",
            field=models.CharField(
                blank=True,
                help_text="Identifiant unique imprimé sur la carte du personnel (ex: 42Emp-24-39/ISI)",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Matricule employé",
            ),
        ),
    ]
