# Generated by Django 5.1.4 on 2026-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_add_matricule_employe"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_qr_token",
            field=models.CharField(
                blank=True,
                help_text="Jeton secret encodé dans le QR code de la carte du personnel, utilisé pour le pointage.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Jeton QR de pointage",
            ),
        ),
    ]
