# Generated by Django 5.1.4 on 2026-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_user_staff_qr_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                help_text='Utilisé pour accorder "Monsieur"/"Madame" dans les messages générés (ex : verrouillage de semestre).',
                max_length=1,
                verbose_name="Genre",
            ),
        ),
    ]
