# Generated by Django 5.1.4 on 2026-07-08 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_role_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FAILED_LOGIN", "Échec de connexion"),
                            ("BRUTE_FORCE", "Tentative force brute"),
                            ("UNAUTHORIZED", "Accès non autorisé"),
                            ("SUSPICIOUS_PATH", "Chemin suspect"),
                            ("ACCOUNT_LOCKED", "Compte verrouillé"),
                            ("SESSION_HIJACK", "Tentative de détournement de session"),
                            ("CSRF_VIOLATION", "Violation CSRF"),
                            ("RATE_LIMIT", "Limite de requêtes dépassée"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Sévérité",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "path",
                    models.CharField(blank=True, max_length=500, verbose_name="Chemin"),
                ),
                (
                    "username_tried",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Identifiant tenté"
                    ),
                ),
                ("details", models.TextField(blank=True, verbose_name="Détails")),
                ("resolved", models.BooleanField(default=False, verbose_name="Résolu")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Résolu par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de sécurité",
                "verbose_name_plural": "Événements de sécurité",
                "db_table": "security_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="security_ev_event_t_efa0a0_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="security_ev_ip_addr_038026_idx",
                    ),
                    models.Index(
                        fields=["severity", "resolved"],
                        name="security_ev_severit_23d5a6_idx",
                    ),
                ],
            },
        ),
    ]
