# Generated by Django 5.1.4 on 2026-07-15 20:33

import django.db.models.deletion
from django.db import migrations, models


def disable_fk(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.connection.cursor().execute("PRAGMA foreign_keys = OFF")


def enable_fk(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.connection.cursor().execute("PRAGMA foreign_keys = ON")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("academic_structure", "0020_fix_faculty_institutconfig_cross_db_fk"),
        ("accounts", "0030_seed_assistante_dg_direction_roles"),
    ]

    operations = [
        migrations.RunPython(disable_fk, reverse_code=enable_fk),
        migrations.AlterField(
            model_name="direction",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directions",
                to="academic_structure.faculty",
                verbose_name="Institut",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="institut_config",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admins",
                to="academic_structure.institutconfig",
                verbose_name="Institut administré",
            ),
        ),
        migrations.RunPython(enable_fk, reverse_code=disable_fk),
    ]
