# Generated by Django 5.1.4 on 2026-07-16 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_structure", "0021_program_level"),
        ("accounts", "0031_fix_faculty_institutconfig_cross_db_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControllerInstitut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institut_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controller_links",
                        to="academic_structure.institutconfig",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlled_institut_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Institut contrôlé",
                "verbose_name_plural": "Instituts contrôlés",
                "db_table": "controller_instituts",
                "unique_together": {("user", "institut_config")},
            },
        ),
    ]
