# Generated by Django 5.1.4 on 2026-07-18 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_controllerinstitut"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformActivationResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Jeton de réinitialisation d'activation",
                "verbose_name_plural": "Jetons de réinitialisation d'activation",
                "db_table": "platform_activation_reset_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Hash du code d'activation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Plateforme activée"
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_reset_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dernière modification par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activation de la plateforme",
                "verbose_name_plural": "Activation de la plateforme",
                "db_table": "platform_activation",
            },
        ),
    ]
