# Generated by Django 5.1.4 on 2026-07-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_platformactivationresettoken_platformactivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformactivation",
            name="env_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="platformactivation",
            name="env_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="platformactivation",
            name="env_tampered",
            field=models.BooleanField(default=False),
        ),
    ]
