# Generated by Django 5.1.4 on 2026-07-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_platformactivation_code_prefix_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformactivation",
            name="env_confirmed_at",
        ),
        migrations.RemoveField(
            model_name="platformactivation",
            name="env_fingerprint",
        ),
        migrations.RemoveField(
            model_name="platformactivation",
            name="env_tampered",
        ),
    ]
