# Generated by Django 5.1.4 on 2026-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_remove_platformactivation_env_confirmed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformactivation",
            name="code_prefix_hash",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Hash des 10 premiers caractères de l'ancien code",
            ),
        ),
    ]
