# Generated by Django 5.1.4 on 2026-07-22 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_candidat_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    db = schema_editor.connection.alias
    Role.objects.using(db).get_or_create(
        name='CANDIDAT',
        defaults={'description': "Compte candidat au portail public d'admission — avant validation de son inscription."}
    )


def remove_candidat_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    db = schema_editor.connection.alias
    Role.objects.using(db).filter(name='CANDIDAT').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_user_groups_user_permissions_db_constraint_false"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("INST_ADMIN", "Administrateur d'institut"),
                    ("SI_ADMIN", "Administrateur du SI"),
                    ("ASSISTANTE_DG", "Assistante du Directeur Général"),
                    ("ADMIN_DIRECTION", "Administrateur de direction"),
                    ("ADMIN_DE", "Directeur des études"),
                    ("ADMIN_DAF", "Directeur Administratif et Financier"),
                    ("ADMIN_COM", "Administrateur Direction (COM)"),
                    ("ADMIN_RH", "Directeur des ressources humaines"),
                    ("ASSISTANTE_DE", "Assistante Directeur des études"),
                    ("ASSISTANTE_DIRECTION", "Assistante de Direction"),
                    ("CIAQ", "CIAQ"),
                    ("CONTROLEUR", "Contrôleur Interne"),
                    ("RESPONSABLE", "Chef de Département"),
                    ("RESPONSABLE_CLASSE", "Responsable de classe"),
                    ("ADJOINT_RESPONSABLE_CLASSE", "Adjoint du responsable de classe"),
                    ("ASSISTANTE", "Assistante de département"),
                    ("COMPTABLE", "Comptable"),
                    ("TRESORIER_GENERAL", "Trésorier Général"),
                    ("CAISSIER", "Caissier"),
                    ("CHARGE_EXAMENS_CONCOURS", "Chargé des Examens & Concours"),
                    ("ENSEIGNANT", "Enseignant"),
                    ("ETUDIANT", "Étudiant"),
                    ("CONTROLE_ACCUEIL", "Contrôle Accueil"),
                    ("CANDIDAT", "Candidat"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.RunPython(create_candidat_role, remove_candidat_role),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_verification_tokens",
            },
        ),
    ]
